### ISSUE TITLE
Crash when running download-schema

### ISSUE THREAD

**Issue by clayne11** [apollographql/apollo-codegen#110]
When I run `download-schema` I get the following exception:

```
$ apollo-codegen download-schema http://localhost:3000/graphql --output graphql-schema.json
Error while fetching introspection query result: Unexpected token I
```

When I run the introspection query in GraphiQL it works fine.

**Comment by dylanscott** [comment]
Is it possible your graphql endpoint is expecting some sort of authorization (e.g. a session cookie)? If GraphiQL is running on the same origin as the endpoint that would just happen automatically for that request whereas you would need to specify it with the `--header` flag from the CLI.

**Comment by clayne11** [comment]
You're right - I just realized there was actually a bug in my request code that I introduced today. Fixed it and all is well.
