### ISSUE TITLE
Allow option to not fail on unused types

### ISSUE THREAD

**Issue by clayne11** [apollographql/apollo-codegen#111]
I have some components in my codebase that I'm not currently using in a query. When I run `generate` it fails GraphQL validation. I'd like the option to not fail in this use case because for me this isn't an error.

**Comment by lewisf** [comment]
@clayne11 thanks! to clarify, your queries fail GraphQL validation because they're actually invalid given your schema? 

We can get `generate` to just throw warnings on these queries instead of failing out right.

**Comment by clayne11** [comment]
No, the queries are valid given the schema. The issue is that I have a
couple fragments that are not being used in a query at the moment (because
their corresponding components are not currently in use).

**Comment by martijnwalraven** [comment]
@clayne11: You'll be happy to know that we removed the `NoUnusedFragments` validation rule in the latest `apollo-codegen` update. Version `0.12.4` has been tagged as `next` for now, but you can install it using `npm install -g apollo-codegen@next`.
