### ISSUE TITLE
Include deprecation information in generated output

### ISSUE THREAD

**Issue by ryangardner** [apollographql/apollo-codegen#114]
to be able to add annotations that can give developers compile-time warnings, or warnings in their IDE (covered in https://github.com/apollographql/apollo-android/issues/488 ) the json output of the codegen tool needs to include the deprecation status and deprecation reason for deprecated types / fields

**Comment by sav007** [comment]
@martijnwalraven what about enum, values of enum can be deprecated as well, here is example of deprecated enum value:
```
{
              "name": "DEPRECATED",
              "description": "Test deprecated enum value",
              "isDeprecated": true,
              "deprecationReason": "For test purpose only"
            }
```

but generated IR doesn't have these fields:
```
{
					"name": "DEPRECATED",
					"description": "Test deprecated enum value"
				}
```

**Comment by martijnwalraven** [comment]
@sav007: Ok, added in 0.12.8!
