### ISSUE TITLE
Empty .TS file generated

### ISSUE THREAD

**Issue by bradmartin** [apollographql/apollo-codegen#121]
I've successfully output the *schema.json* file but when I run the `generate` command
```
apollo-codegen generate **/*.graphql --schema schema.json --target typescript --output schema.ts
```
 I get an empty schema.ts file with the following output:

```
//  This file was automatically generated and should not be edited.
/* tslint:disable */
/* tslint:enable */
```

Not sure where to start on tracking this down. The schema.json file looks correct, is about 60+kb of data so it seems to be correct, at least in terms of it working 😄 . I'd be glad to help debug the issue if some pointers can be provided.

cc @intelligentdan

**Comment by altschuler** [comment]
Do you have any `.graphql` files with queries in them? I did the same thing and was confused because I thought the whole schema would just be output, but the tool generates types for your defined queries.

**Comment by intelligentDan** [comment]
Ah, that makes sense.  I was confused by what the .graphql files actually
were supposed to contain, I couldn't find the documentation.  Thank you!

On Wed, May 24, 2017 at 12:56 AM, Simon Altschuler <notifications@github.com

**Comment by altschuler** [comment]
If you're using `graphql-tag` (the `` gql`...` ``) you can replace the `**/*.graphql` with `**/*.ts` and it'll find those and generate types for them :)

**Comment by rricard** [comment]
I'll close this issue and point to the issue #140 for the lack of documentation that needs to be fixed.
