### ISSUE TITLE
Flow array elements should be marked as "maybe"

### ISSUE THREAD

**Issue by finneganh** [apollographql/apollo-codegen#122]
If a GraphQL list has a nullable element, its Flow element type should be prefixed with `?`.

An incorrect test snapshot is here: 

https://github.com/apollographql/apollo-codegen/blob/master/test/flow/__snapshots__/codeGeneration.js.snap#L421

Since the type of the `friends` field is `[Character]`, the generated Flow type should be:

```
  friends: ?Array< ?{|
    // The name of the character
    name: string,
  |} >,
```

instead of:
```
  friends: ?Array< {|
    // The name of the character
    name: string,
  |} >,
```

**Comment by rricard** [comment]
@finneganh Completely agree, this is a bad error! I'll take a look at that right away!
