### ISSUE TITLE
Latest versions not being published

### ISSUE THREAD

**Issue by lemonmade** [apollographql/apollo-codegen#131]
Despite the latest version clearly being 0.12.x, the latest version I can install from NPM/ Yarn is still 0.10.13 (see the version at the top of the page on https://yarnpkg.com/en/package/apollo-codegen).

**Comment by martijnwalraven** [comment]
Yeah, 0.12.x is tagged as `next` for now, not `latest`, because the new Swift target requires a beta version of Apollo iOS and I don't want to break the current version. You can use `npm install -g apollo-codegen@next` to install it.
