### ISSUE TITLE
flow: Nullable properties in query and mutation variables should be output as optional

### ISSUE THREAD

**Issue by yenbekbay** [apollographql/apollo-codegen#134]
The generated flow type
```js
export type SomeQueryVariables = {
  fieldName: ?string,
};
```

should preferably be 
```js
export type SomeQueryVariables = {
  fieldName?: ?string,
};
```

since `fieldName` is not required.

I could fix this by monkey patching https://github.com/apollographql/apollo-codegen/blob/master/src/flow/language.js#L63 as
```js
const isNullableVariableProperty =
  generator.scopeStack[0].typeName.endsWith('Variables') &&
  typeName.startsWith('?');

generator.printOnNewline(
  `${propertyName}${isNullableVariableProperty ? '?' : ''}: ${typeName}`,
);
```

but I don't think that's a good solution.

**Comment by rricard** [comment]
@yenbekbay Thanks for the report. I think we can do something simpler. Can you try to put your monkey patch into a PR so we can check it out and define what to do.
