### ISSUE TITLE
--add-typename is being generated regardless of the configuration

### ISSUE THREAD

**Issue by gajus** [apollographql/apollo-codegen#137]
I have tried `--add-typename`, `--add-typename false` and in both cases the `__typeName` is being added:

```js
export type GetGeolocationByIpQuery = {|
  visitor: {|
    __typename: string,
    geolocation: {|
      __typename: string,
      address: string,
      coordinates: {|
        __typename: string,
        latitude: number,
        longitude: number,
      |},
    |},
  |},
|};

```

**Comment by rricard** [comment]
@lewisf I don't know much about the `__typename` stuff yet, but from what I understand, the Flow implementation does not handle that correctly.

**Comment by lewisf** [comment]
yeah, this will get fixed soon

**Comment by rricard** [comment]
Indeed, I think this change will solve the bug: https://github.com/apollographql/apollo-codegen/pull/143/files#diff-d9d9214113dea1c364abd4ba3c70be11R133

**Comment by lewisf** [comment]
This should work now.

The option is `--addTypename`, and if you don't want to add __typename, just don't include the flag. However, when using Flow / Typescript you might want to use it. Refer to the new section in the README.md labeled "Typescript and Flow"
