### ISSUE TITLE
'apollo-codegen --target ts' throws error

### ISSUE THREAD

**Issue by louislarry** [apollographql/apollo-codegen#144]
When I use the latest apollo-codegen from npm.
```
$ ./node_modules/.bin/apollo-codegen generate *.ts --target ts
Syntax Error /private/tmp/x/user-grid-list.model.ts (1:1) Unexpected Name "import"

1: import { DocumentNode } from 'graphql';
   ^
2:
```

But when I build apollo-codegen from master, it does work as expected.

**Comment by keplersj** [comment]
Same is occurring with flow and attempting to use the tags functionality.

**Comment by lewisf** [comment]
I'm going to try to reproduce this

**Comment by lewisf** [comment]
I can't reproduce this for whatever reason -- can somebody who's encountering this issue throw up a quick repository showcasing this problem?

**Comment by louislarry** [comment]
The repo master version works fine for me.  The npm one spits out error..

Louis.

**Comment by lewisf** [comment]
This is really odd. I can't reproduce it, and I've tried a bunch of times. It'd really help if someone could push a minimal reproduction case to a repo.

It isn't clear to me why apollo-codegen, or any of it's third-party dependencies, would try to load/parse a module that it doesn't own.

**Comment by rricard** [comment]
@martijnwalraven Do you think it's related to the changes we made recently while switching to TS?

**Comment by martijnwalraven** [comment]
@rricard: Those haven't been released yet, except as `next`.

**Comment by rricard** [comment]
Okay so I'm as clueless as you all here...

**Comment by martijnwalraven** [comment]
Well, seeing as `master` is working and we're about to release a new version, I hope this problem will solve itself!

**Comment by rricard** [comment]
🤞

**Comment by louislarry** [comment]
The new npm version 0.13.0 works as expected.

albeit `package.json` seems to be missing `source-map-support` as dependency.
```
$ ./node_modules/.bin/apollo-codegen generate ./user-grid-list.model.ts --target ts
module.js:487
    throw err;
    ^

Error: Cannot find module 'source-map-support/register'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
```

after `npm i source-map-support` things works fine for me.

**Comment by martijnwalraven** [comment]
@louislarry: Ah, good catch! I'm not sure why `source-map-support` was removed, but the reason we didn't notice is because it was installed as an implicit dev dependency of `jest`. I've added it back and released 0.13.1.

**Comment by louislarry** [comment]
0.13.1 works great 👍

**Comment by lewisf** [comment]
Great to hear this is fixed!
