### ISSUE TITLE
generating flow types

### ISSUE THREAD

**Issue by hyusetiawan** [apollographql/apollo-codegen#154]
Following the examples laid out in the docs, the best practice it seems to put the query with the component, which makes sense to me.
At the same time, if I want to generate flow types, it asks for .graphql files, which means I have to separate out the query to its own files and name them *.graphql.

My question is, how do I put the query with the react component and then generate the flow types?

Thank you

**Comment by martijnwalraven** [comment]
You can also use [`gql` template tags](https://github.com/apollographql/apollo-codegen#gql-template-support) instead of separate `.graphql` files.

**Comment by hyusetiawan** [comment]
@martijnwalraven  I dont think that works, it says that it can parse javascript files but it throws an error on the first line of javascript:

```
// @flow
   ^
2: import React, {Component} from 'react'
```

this is the command I use:
`apollo-codegen generate  component/**/*.js  --schema schema.json --target flow`

I would like to also point out that the option to add __typename --addTypeName is not recognized.
per help command out here:
```
apollo-codegen generate [input...]

Options:
  --help                        Show help                              [boolean]
  --version                     Show version number                    [boolean]
  --schema                      Path to GraphQL schema file
                                    [string] [required] [default: "schema.json"]
  --output                      Output directory for the generated files[string]
  --target                      Code generation target language
       [choices: "swift", "json", "ts", "typescript", "flow"] [default: "swift"]
  --passthrough-custom-scalars  Don't attempt to map custom scalars [temporary
                                option]                         [default: false]
  --custom-scalars-prefix       Prefix for custom scalars. (Implies that
                                passthrough-custom-scalars is true if set)
                                                          [string] [default: ""]
```

**Comment by lewisf** [comment]
@hyusetiawan , what is the output of `apollo-codegen --version`?

**Comment by hyusetiawan** [comment]
@lewisf  this is the output
0.10.13

**Comment by lewisf** [comment]
@hyusetiawan fyi, 0.10.13 is an old release that doesn't have support for *.js files. You'll want to use apollo-codegen@latest
