### ISSUE TITLE
TypeError: Cannot read property 'existsSync' of undefined

### ISSUE THREAD

**Issue by steida** [apollographql/apollo-codegen#157]
`apollo-codegen introspect-schema schema.graphql --output schema.json`

It looks like a code is wrongly compiled.

**Comment by lewisf** [comment]
this was addressed in #153, @martijnwalraven let's cut a new release to pull this in?

**Comment by magnushiie** [comment]
The latest release 0.14.0 from yesterday still seems to not include this fix.

**Comment by lewisf** [comment]
Sorry about that, I can reproduce and will take a look

**Comment by lewisf** [comment]
@magnushiie are you still seeing "TypeError: Cannot read property 'existsSync' of undefined"

or is `apollo-codegen introspect-schema schema.graphql --output schema.json` failing with another error?

**Comment by magnushiie** [comment]
Yes, I'm seeing the same error. The version is 0.14.0, `node_modules/apollo-codegen/lib/introspectSchema.js` has the following lines:
11:
```js
const fs_1 = require("fs");
```
24:
```js
        if (!fs_1.default.existsSync(schemaPath)) {
```

I.e. it seems fs is still imported as ```import fs from 'fs';``` instead of ```import * as fs from 'fs';```

**Comment by lewisf** [comment]
It looks like 0.14 is broken but a fresh build of master works fine :(

**Comment by martijnwalraven** [comment]
@magnushiie: Can you try again with 0.14.3? I'm not sure where things go wrong, but it seems npm doesn't execute the `prepare` script when publishing, meaning the TypeScript compiler won't run and `lib` won't be up to date. So I've reverted to using `prepublish` for now.

**Comment by martijnwalraven** [comment]
Going to close this because I believe it has been fixed. Please reopen if that isn't the case.

**Comment by magnushiie** [comment]
Sorry for late response, yes, it's fixed, thank you!

**Comment by lukaszgrudnik** [comment]
**import * as fs from 'fs'** instead of **import fs from 'fs'**
