### ISSUE TITLE
Can this tool be used for server code?

### ISSUE THREAD

**Issue by Surreal9** [apollographql/apollo-codegen#164]
I see from the README references to query documents; My server currently only has a schema defined along with resolvers.. if I try to run the command to generate a typescript file I get:

```
> apollo-codegen generate **/*.graphql --schema schema.json --target typescript --output schema.ts

.../apollo-codegen/test/starwars/AnonymousQuery.graphql: Apollo does not support anonymous operations
.../apollo-codegen/test/starwars/TypenameAlias.graphql: Apollo needs to be able to insert __typename when needed, please do not use it as an alias
error: Validation of GraphQL query document failed
```

I notice the glob looking for .graphql files, which I currently don't have on my server. Just wondering if I can generate types from the schema alone; thanks!

**Comment by lewisf** [comment]
Firstly, it looks like the glob is picking up stuff in `node_modules` AND we're publishing tests. But that's a separate issue that needs to get fixed.

To answer your question @Surreal9: we cross reference against query documents to generate types because you'd usually specify exactly what fields you want in a query. Are you expecting responses with the full set of fields on your server?

**Comment by Surreal9** [comment]
Thanks for your response. Perhaps those errors are relating to the fact that I could only get apollo-codegen to work properly when I installed it locally; when installing globally and trying to run apollo-codgen I get the error:

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/apollo-codegen/lib/compilation.js:6:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

Perhaps that is the separate issue..

In any case for my original question I am trying to generate typescript defs for the types I've defined in my graphql schema files on the server. I had been defining them as per [the graphql-tools docs](http://dev.apollodata.com/tools/graphql-tools/generate-schema.html#modularizing), which has the files basically formatted as an es6 module (with an export default statement), and didn't seem to be picked up when I used the glob for my schema files (which I've named .gql.ts since TypeScript didn't seem to want to read them as .gql files..)

I may try re-writing them as 'raw .graphql' files which should be the format this tool expects and then adjust the means I am reading them in my server.

**Comment by Surreal9** [comment]
I'm just hoping to use these types in my resolvers for the first parameter to be strongly typed.

**Comment by lewisf** [comment]
I see. Unfortunately this use case isn't supported currently :(

For the time being: There is an existing project that does what you want for flow types: https://github.com/joarwilk/gql2flow. It might be possible to convert the generated flow types to typescript types.

We might be able to support this use case in the future, but it hasn't been on our roadmap as of yet.

**Comment by Surreal9** [comment]
Ah ok understood, it seems [graphtype](https://github.com/2fd/graphtype) seems to do the job. I'm still glad to leverage apollo-codegen to generate the .json schema from my graphql schema files. Thanks!
