### ISSUE TITLE
Invalid typescript generated

### ISSUE THREAD

**Issue by skeswa** [apollographql/apollo-codegen#179]
I just can't seem to figure out what I'm doing wrong. It seems that nobody has had this issue. The generated typescript references a type (User) that is not defined.

My schema:
```
# The root definition of the schema.
schema {
  query: Query
  mutation: Mutation
}

# The query type, represents all of the entry points into our object graph.
type Query {
  me: User
  feed(offset: Int!, limit: Int!): [Post]!
}

# The mutation type, represents all updates we can make to our data.
type Mutation {
  like(postId: ID!): Post!
  createPost(message: String, imageUrl: String): Post!
}

# Declare a Date type for use in the rest of the model.
scalar Date

# Represents a user.
type User {
  id: ID!
  dateJoined: Date!
  handle: String!
  followers(offset: Int!, limit: Int!): [User]!
  following(offset: Int!, limit: Int!): [User]!
  name: String!
  profilePictureUrl: String
  posts(offset: Int!, limit: Int!): [Post]!
  totalFollowers: Int!
  totalFollowing: Int!
  totalPosts: Int!
}

# Represents a post.
type Post {
  id: ID!
  dateCreated: Date!
  dateLastEdited: Date!
  imageUrl: String
  likers(offset: Int!, limit: Int!): [User]!
  message: String
  poster: User!
  comments(offset: Int!, limit: Int!): [Comment]!
  totalLikes: Int!
  totalComments: Int!
}

# Represents a comment.
type Comment {
  message: String!
  dateCreated: Date!
  commenter: User!
}
```

My query file:
```
query Me {
  me
}
```

The generated typescript:
```
/* tslint:disable */
//  This file was automatically generated and should not be edited.

export type MeQuery = {
  me: User | null,
};
/* tslint:enable */
```

**Comment by lewisf** [comment]
@skeswa can you clarify what you were expecting to see to help us out?

**Comment by rricard** [comment]
@lewisf I think @skeswa expected to see the User type appearing. Unfortunately, @skeswa this query is not right, you should expand your `me` into a SelectionSet since `me` is not a Scalar type. At this point, we will be able to generate for you the nested type, but in this situation, our generation considers that `User` is a scalar type since you did not expand it. Here is a query that would work:

```graphql
query Me {
  me {
    id
  }
}
```

**Comment by skeswa** [comment]
Thanks for the explanation! It would be great if there were some sort of warning to this tool in cases like these. It may be obvious to people very familiar with GraphQL, but to me this issue was perplexing.

**Comment by rricard** [comment]
@skeswa unfortunately, for now, Scalar types are a bit weird since you may create your own...
