### ISSUE TITLE
generate path ** doesn't match arbitrarily nested files

### ISSUE THREAD

**Issue by gniquil** [apollographql/apollo-codegen#180]
When I used the command:
```
apollo-codegen generate ./src/**/*.js ...
```
This doesn't generate files for say `./src/one/two/three.js`. But I tried the following and it works:
```
apollo-codegen generate ./src/**/*.js ./src/**/**/*.js ./src/**/**/**/*.js ...
```

Is this the correct behavior? This doesn't feel intuitive.

**Comment by lewisf** [comment]
@gniquil what shell are you using? shell glob expansion may vary.

what if you did `apollo-codegen generate "./src/**/*.js"`

**Comment by gniquil** [comment]
@lewisf I guess bash; I put it in npm script and have npm-watch auto trigger codegen on file changes.

**Comment by lewisf** [comment]
@gniquil we defer to `node-glob` to do glob resolution. try quoting your `"./src/**/*.js"` glob

**Comment by gniquil** [comment]
@lewisf adding quotes worked (didn't test it in shell, but worked when put int package.json scripts)!

**Comment by iamdanthedev** [comment]
@lewisf thanks that helps!
