### ISSUE TITLE
Apollo does not support anonymous operations

### ISSUE THREAD

**Issue by agborkowski** [apollographql/apollo-codegen#184]
version: apollo-codegen 0.15.2

i execute query in graphiql
`query { getAllCustomers {id} }`

i gets data.getAllCustomers[ids...]

````
{
  "data": {
    "getAllCustomers": [
      {
        "id": "34"
````
then i want to execute query under apollo-client/angular-apollo

so i continue with codegen

- apollo-codegen download-schema http://localhost:3000/graphql --output schema.json
- apollo-codegen generate src/**/*.gql --schema schema.json --target typescript --output src/app/graphql/schema.ts

[schema/json/js](https://gist.github.com/agborkowski/b1c4f05b32fab354933f917625745142)

i have only one .gql file with the same query like i executed in graphiql:
`query { getAllCustomers {id} }`

but schema.ts wont genrate with error

```
.../main/customers/_graphql/getCustomers.gql: Apollo does not support anonymous operations
error: Validation of GraphQL query document failed
````
# Update

if found problem query withink works in graphql-tag and gprahiql wont generate type script to solve above problem is add

````
query SOMESTRING { getAllCustomers {id name symbol} }
````

then apolo codegen will generate 

````
export type SOMESTINGQuery = {
  getAllCustomers:  Array< {
`````

**Comment by rricard** [comment]
Yes, we need to name the types we generate so we can't really support anonymous queries.

**Comment by johndpope** [comment]
so the example 
query SOMESTRING { getAllCustomers {id name symbol} }
 is brilliant. 

in the code - 
you need to throw a warning and say to users
query INSERTQUERYNAMEHERE { getAllCustomers {id name symbol} }
maybe even link back here
https://github.com/apollographql/apollo-codegen/issues/184

or perhaps you could randomize some name? like heroku?

**Comment by langpavel** [comment]
You really MUST report file name where the error happened.
I have app with 50 queries and I really don't want check every file manually

**Comment by mcmar** [comment]
@rricard Do you think we can re-open this issue in light of @langpavel's comment that we need to report the file name where the error occurred. Checking every query manually is an unreasonable solution to this

**Comment by giovannibenussi** [comment]
I was able to debug this by adding temporary logs to the file where the issue was being raised (not the ideal, but it worked for me):

```
// /usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/client.js
if (!definition.name) {
  console.log('definition', definition)
  console.log('document', document)
}
```

Document will give you information about the file being evaluated so you will be able to solve the issue!

**Comment by Enalmada** [comment]
In my case the error was coming from an old commented out query and I had to remove the comment to get it to work
```
/*
const ROUND_LIST = gql`
  {
    rounds {
      ...FullRound
    }
  }
  ${fullRoundFragment}
`;
*/
```

**Comment by ardok** [comment]
Can we add this tracing? As simple as @giovannibenussi console logging would help a tremendous amount.
I finally figured out my error after printing out the `document`.

**Comment by camsjams** [comment]
The other side of the coin here is what if we just want to skip anonymous operations?
