### ISSUE TITLE
Generated constructors are incorrect

### ISSUE THREAD

**Issue by stevenb9** [apollographql/apollo-codegen#233]
I'm trying to create a mock object for my "TVGuideQuery" eg.:

```
...
 var channel =  TVGuideQuery.Data.ChannelList.Channel(id: "",
                                                      expiry: "",
                                                      pageInfo: nil,
                                                      totalCount: 100,
                                                      edges: nil)

var channelList = TVGuideQuery.Data.ChannelList(id: "",
                                                expiry: "",
                                                name: "",
                                                channels: channel)
```

I would expect the channel in my channelList variable to have the value of channel, however when constructing the data like this, subObjects do NOT seem to be added and instead will stay nil.

to fix this I would have to add this line and manually re-assign the channel object to the channel param, only then it will take the correct value:
`        channelList.channels = channel`

Cause:
 ```
     public init(eventsAt: EventsAt? = nil) {
        self.init(snapshot: ["__typename": "Channel", "eventsAt": eventsAt])
      }

      public var __typename: String {
        get {
          return snapshot["__typename"]! as! String
        }
        set {
          snapshot.updateValue(newValue, forKey: "__typename")
        }
      }

      public var eventsAt: EventsAt? {
        get {
          return (snapshot["eventsAt"]! as! Snapshot?).flatMap { EventsAt(snapshot: $0) }
        }
        set {
          snapshot.updateValue(newValue?.snapshot, forKey: "eventsAt")
        }
      }
```
These are the generated initializers when using the init with all parameters, the eventsAt object is put directly in the snapshot, however, when setting it we are adding the eventsAt.snapshot. 
I'm using codegen v0.16.5

**Comment by martijnwalraven** [comment]
Ah, good catch! `apollo-codegen` is in a bit of a flux right now, with large parts rewritten to fix some issues, and I'm now working on a new Apollo iOS release to match that. I'll make sure to fix this as well. I plan to have a beta of the new version out after the weekend.
