### ISSUE TITLE
.graphqlconfig support

### ISSUE THREAD

**Issue by lydell** [apollographql/apollo-codegen#235]
Can we add support for [.graphqlconfig](https://github.com/graphcool/graphql-config) (just like [apollographql/eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql/#example-config-when-using-graphqlconfig)), as an alternative to the `--schema` option? That would be very useful! I can make a PR if it is accepted :)

**Comment by trevordmiller** [comment]
This would be great! Blog post about it for reference: https://blog.graph.cool/new-tooling-to-improve-your-graphql-workflows-7240c81e1ba3

**Comment by martijnwalraven** [comment]
Definitely interested in adding support for `.graphqlconfig`, so a PR is very welcome!

**Comment by trevordmiller** [comment]
@lydell do you plan to PR this then?

**Comment by trevordmiller** [comment]
@lydell Awesome, thank you! I've added a note to a blog post I wrote about generating things (like types) from a schema file using a `.graphqlconfig`: https://ropig.com/blog/using-graphql-schema-supercharge-team-collaboration/
