### ISSUE TITLE
apollo-codegen - how to set output file relative to source file

### ISSUE THREAD

**Issue by pie6k** [apollographql/apollo-codegen#239]
My command is like:

`apollo-codegen generate \"./src/**/*.js\" --schema src/gql/schema.json --target flow --tag-name gql --output src/gql/types.js`

So basically, types from all of my `js` files that have `gql` tag are grouped together inside single file: `src/gql/types.js`. 

I'd like to have one 'small' file in the same folder as every `js` file with `gql` tag with types only for this specific file.

Is this possible?

**Comment by martijnwalraven** [comment]
This isn't currently possible, but see https://github.com/apollographql/apollo-codegen/issues/218 for a similar feature request.
