### ISSUE TITLE
Validation code does what is not intended?

### ISSUE THREAD

**Issue by nsf** [apollographql/apollo-codegen#242]
I was wondering why apollo-codegen doesn't perform many validations as it should. And I looked at the code and saw this fragment:

https://github.com/apollographql/apollo-codegen/blob/dc61650e753ba23ae5c67697267232799bd1ed9f/src/validation.ts#L27

I think it does the opposite of what it tells, e.g. take a look at this example in node:

    > var toBeRemoved = [1, 2];
    undefined
    > var arr = [1, 2, 3, 4, 5, 6, 7, 8];
    undefined
    > arr.filter(rule => toBeRemoved.includes(rule))
    [ 1, 2 ]

Instead of removing the "to be removed" rules, it keeps them?

Is this intended?

**Comment by martijnwalraven** [comment]
Ah, good catch! That's definitely not intended.
