### ISSUE TITLE
Flow output is putting invalid spaces in array declarations

### ISSUE THREAD

**Issue by danieljvdm** [apollographql/apollo-codegen#249]
`apollo-codegen generate ./queries/**/*.js --schema schema.json --target flow --output schema.flow.js -- addTypename` outputs the following for arrays:

```
export type StringInputType = {|
  eq?: ?string,
  in?: ?Array< string >,
|};
```

Notice it should be `?Array<string>` without the extra spaces.

Apollo codegen 0.16.5
Flow: 0.54

**Comment by lewisf** [comment]
Try using the latest `flow-modern` target in newer releases, thanks! Manually constructing strings was really cumbersome and we've moved to working with ASTNodes that should print the correct syntax you're looking for
