### ISSUE TITLE
[JS/TS/Flow] Read GraphQL documents inside template strings

### ISSUE THREAD

**Issue by rricard** [apollographql/apollo-codegen#25]
Followup to https://github.com/apollostack/apollo-codegen/pull/24#issuecomment-266221363

We need to support extracting queries from template strings.

- [x] Extract from `gql` tags
- [ ] Extract and infer a fragment name for `Relay.QL` tags

**Comment by rricard** [comment]
@chollier `Relay.QL` will require more work than just finding template strings since Relay dynamically generates the queries. We'll maybe need your contribution for that!

**Comment by chollier** [comment]
Indeed I was thinking the same, we don't name fragments in Relay. 
I'm thinking we could maybe infer the fragment name from the filename?

I also know that with Relay2 it's planned that their would be a way to statically traverse the code, extract the Relay Queries and eventually store them as persisted queries (https://www.youtube.com/watch?v=OEfUBN9dAI8)

Also, they recently introduced babel-plugin-graphql ( https://github.com/facebook/relay/commit/c51c351de44619d1e5a05143dafad97d341d8469 ), it gives clues on how fragments will be named in the future.

**Comment by jtmthf** [comment]
I was wondering for this implementation how a parser would be chosen? Would it be inferred for example that maybe [ntypescript](https://github.com/TypeStrong/ntypescript) would be used for typescript generation and [babylon](https://github.com/babel/babylon) would be used for flow generation? Or would setting the specific parser and perhaps it's setting be configurable from the CLI.

By having multiple parsers, they could each conform to an implementation interface in which they would return an array of plain text graphql source and optional paths. A modified version of `loadAndMergeQueryDocuments` would then create the merged AST. The path of execution would then look like:

CLI -> Language Specific Parser -> Standard Compiler -> Language Specific Generator -> Output

For this approach to work, the extraction of source from literal .graphql files would have to be moved into it's own "parser", but that implementation would be trivial.

**Comment by stubailo** [comment]
I don't think we need a parser for this at all, a simple regex seems to work just fine: https://github.com/Poincare/persistgraphql/blob/master/src/extractFromJS.ts

**Comment by stubailo** [comment]
(BTW that's the codebase for a query persisting tool for Apollo we're planning on announcing very soon)

**Comment by Grmiade** [comment]
Any updates on this?

**Comment by lewisf** [comment]
@Grmiade there has been a lot of talk around this topic but no progress yet because we've been trying to figure out how to create a generalized utility around extracting gql.

**Comment by itajaja** [comment]
I took a very rough stub at this in https://github.com/apollographql/apollo-codegen/pull/113

**Comment by lewisf** [comment]
thanks @itajaja i'll take a look

**Comment by lewisf** [comment]
I merged in #113 @itajaja thanks! we do want to add docs/tests for it -- and in the original issue it would be cool to support arbitrary template tags so I'm going to leave this issue open until we resolve those

**Comment by rricard** [comment]
We'll track what's left to do in #140. Thank you for the work already done!
