### ISSUE TITLE
Sort enums for cleaner diff

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-codegen#250]
apollo-codegen doesn’t seem to consistently order enum values so a small schema change might result in a noisy diff.

Should be easy enough to sort alphabetically

**Comment by martijnwalraven** [comment]
Hmmm, I wonder why the order of enum values in `graphql-js` isn't stable, because that's where we get them from. Ideally, the order would reflect the type definition in the schema I think.
