### ISSUE TITLE
Swift > Fragment fields queried on Interface do not get populated

### ISSUE THREAD

**Issue by IgorLipovac** [apollographql/apollo-codegen#253]
### Problem description:
- Imagine we have an interface called `Event` and 3 types implementing the interface: `ActiveEvent`, `CancelledEvent`, `ExpiredEvent`. 
- We would like to query a fragment called `EventItemFields` with a set of properties that all of our implementations contain and we want to do it on `Event` since we don't really care which implementation is in question.
- If we try to query `EventItemFields` on an interface, `Event` in our case, codegen creates the necessary code & structs with fields that we query. However when we try to access them, it causes a crash because we're force unwrapping a nil field in `snapshot` dict. 

### Fragment: 
```
fragment EventItemFields on Event {
    name
    date
}
```

### Non-working Example
```
query GetEvent ($id: ID!) {
    node(id: $id) {
          ... EventItemFields
    }
}
```
- crashes when trying to access `name` or `date` 

### Working example:
```
query GetEvent ($id: ID!) {
    node(id: $id) {
        ... on ActiveEvent {
            ... EventItemFields
        }

        ... on CancelledEvent {
            ... EventItemFields
        }

        ... on ExpiredEvent {
            ... EventItemFields
        }
    }
}
```
- works but we have to check through `asActiveEvent` / `asCancelledEvent` / `asExpiredEvent`, and we really wanted to avoid checking for concrete implementation

### Final notes
- Can you please check if this is expected behaviour and I'm doing something wrong?
- **I can confirm that non-working example actually works** with `Apollo 0.5.6` and codegen versions `0.10.x`

**Comment by martijnwalraven** [comment]
@IgorLipovac: What version of Apollo iOS does this occur with? Did you try 0.7.0-alpha.5?

**Comment by IgorLipovac** [comment]
Happens on`0.6.5`. I will try the latest one and let you know

**Comment by IgorLipovac** [comment]
Hi @martijnwalraven , after adapting to `0.7.0-alpha.5` the issue is gone! Thanks. Do you have a rough estimate when will this cycle result in a release version?

**Comment by martijnwalraven** [comment]
@IgorLipovac: Good to hear! I hope we can release a new version within the next two weeks.

**Comment by IgorLipovac** [comment]
Hello @martijnwalraven , I'm experiencing the same issue now, with `0.7.0` release, code-gen version `0.17.2`.
