### ISSUE TITLE
bug fix - support deprecated directive. 

### ISSUE THREAD

**Issue by johndpope** [apollographql/apollo-codegen#254]
series_slug: String @deprecated(reason: "Use seriesSlug instead")
  season_slug: String @deprecated(reason: "Use seasonSlug instead")

.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
.../Documents/gitWorkspace/BAM/schema.graphql: Unknown directive "deprecated".
error: Validation of GraphQL query document failed

**Comment by martijnwalraven** [comment]
`apollo-codegen` certainly supports deprecation information in schemas, and should also support constructing them through a `@deprecated` directive in the schema language.

From your output, it seems you might be trying to use `schema.graphql` as a query document, but it should be specified through the `--schema` option.

**Comment by johndpope** [comment]
I'll close this in favor of https://github.com/apollographql/apollo-codegen/issues/255
