### ISSUE TITLE
empty swift code generated from schema

### ISSUE THREAD

**Issue by johndpope** [apollographql/apollo-codegen#255]
steps to recreate

clone repo 
install using
npm install .

apollo-codegen introspect-schema  https://search-api-wwe-mock.bamgrid.com/svc/search/v2/graphql  --output schema.json

apollo-codegen introspect-schema schema.graphql --output schema.json

apollo-codegen generate *.graphql \
           --schema schema.json \
           --target swift \
           --output API.swift

apollo-codegen --version
0.17.0-alpha.8

**Comment by martijnwalraven** [comment]
I'm not sure what you'd expect `apollo-codegen introspect-schema schema.graphql --output schema.json` to do, but you only need `schema.json` for the schema. You will need to add `.graphql` query documents with your queries and mutations however, otherwise there is nothing to generate.

**Comment by johndpope** [comment]
can't it spit out the models with unmapper / unboxer?

that's how this repo rolls and I was expecting this one to do the same.
https://github.com/tberman/graphql-swift-codegen

eg.
<img width="963" alt="screen shot 2017-09-27 at 4 46 23 pm" src="https://user-images.githubusercontent.com/289994/30936965-77e2ee9a-a3a3-11e7-85c0-938f8064824a.png">

eg

struct PhotoAsset: Unboxable{
    
    let contentId: String!
    let type: String!
    let tags: [Tag]
    let  altText: String
    let caption: String
    let  credit: String
    let   headline: String
    let   rawImage: String
    let   width: Int
    let   height: Int
    let   inning: String
    let   purchaseUrl: String
    let   masterCuts: [MasterCut]
    let  photos: [Photo]
    let  timestamp: String
    let  title: String
    
    init(unboxer: Unboxer) throws {
        contentId =  unboxer.unbox(key:"contentId")
        type =  unboxer.unbox(key:"type")
        tags =  try  unboxer.unbox(key:"tags")
        altText =  try  unboxer.unbox(key:"altText")
        caption =  try  unboxer.unbox(key:"caption")
        credit =  try  unboxer.unbox(key:"credit")
        headline =  try  unboxer.unbox(key:"headline")
        rawImage =  try  unboxer.unbox(key:"rawImage")
        width =  try  unboxer.unbox(key:"width")
        height =  try  unboxer.unbox(key:"height")
        inning =  try  unboxer.unbox(key:"inning")
        purchaseUrl =  try  unboxer.unbox(key:"purchaseUrl")
        masterCuts =  try  unboxer.unbox(key:"masterCuts")
        photos =  try  unboxer.unbox(key:"photos")
        timestamp =  try  unboxer.unbox(key:"timestamp")
        title =  try  unboxer.unbox(key:"title")

    }
    
}

**Comment by johndpope** [comment]
if not - maybe best to throw a warning 
you must craft queries only. Model generation not supported.

**Comment by martijnwalraven** [comment]
Generating models from a schema is fundamentally unsafe, because queries only return subsets of fields from objects. That's why we generate query-specific types, with just the data that you're actually requesting. See [this blog post](https://dev-blog.apollodata.com/mapping-graphql-types-to-swift-aa85e5693db4) for more background.

**Comment by johndpope** [comment]
that's sound reasoning. but do consider adding a  warning that would help noobs.
I'm working on 'unsafe' model generation here. upgraded to swift 4. 
if variables are optional - unboxer can get around this. 
https://github.com/johndpope/graphql-swift-codegen

**Comment by johndpope** [comment]
The link you sent explaining query models vs typed modes is excellent and I will be taking your approach here. 

Seeing some code generated from test would be good. Maybe just a link to some starwars canned queries in read me. I’m still digging through code will submit PR when appropriate.

**Comment by martijnwalraven** [comment]
If you're interested in Swift code specifically (`apollo-codegen` is also used to generate TypeScript and Flow), you may want to take a look at [the Star Wars tests in the Apollo iOS repository](https://github.com/apollographql/apollo-ios/tree/master/Tests/StarWarsAPI).
