### ISSUE TITLE
Codegen doesn't support default values for enum and custom scalar lists

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-codegen#256]
Having this in schema:
```json
{
              "name": "listOfCustomScalar",
              "description": "for test purpose only",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "Date",
                  "ofType": null
                }
              },
              "defaultValue": "[\"2017-04-16\", \"2017-04-17\", \"2017-04-18\"]"
            },
            {
              "name": "listOfEnums",
              "description": "for test purpose only",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "ENUM",
                  "name": "Episode",
                  "ofType": null
                }
              },
              "defaultValue": "[\"JEDI\", \"EMPIRE\"]"
            }
```

generates next IR:
```json
{
					"name": "listOfCustomScalar",
					"description": "for test purpose only",
					"type": "[Date]",
					"defaultValue": [
						false,
						false,
						false
					]
				},
				{
					"name": "listOfEnums",
					"description": "for test purpose only",
					"type": "[Episode]"
				}
```

Where default values for list of dates are broken and ignored for enum list.

**Comment by martijnwalraven** [comment]
It turns out we didn't properly serialize default values for input object fields at all, it was kind of coincidence we passed through the `graphql-js` values. I've now added code to serialize input object fields. That seems to fix most issues, but the default value of input object fields for
custom scalars always seems to be `false` in the object coming from `graphql-js`, so it may be a bug there.

**Comment by sav007** [comment]
@martijnwalraven I guess we need to fix the enum case for sure, but with custom scalar types is tricky one as it requires the custom type adapter as an argument to be passed to the constructor (`init`). I would rather to omit this case on Android for now (ignore default values for any custom scalar types for input objects) as known limitation, what do you think?

**Comment by martijnwalraven** [comment]
I think it's ok to ignore default values for any custom scalar types for input objects or now. Maybe I'm missing something here, but that should only affect the cache key right? Or is there another way you're using default values?

**Comment by sav007** [comment]
The defaults values are used for builders as well, when you build Input object.

**Comment by martijnwalraven** [comment]
Ah, that shouldn't be necessary I think. The idea is that if you leave out a field, the server will substitute a default value. You don't have to do this on the client.

**Comment by sav007** [comment]
Yeah that's true, hm I guess this issue is legacy, as we didn't have `Input` wrapper to distinct  if value was set or not before, so that's why we had to have default values. We can completely ignore default values I believe . Is it true on iOS?

**Comment by martijnwalraven** [comment]
Yeah, we currently don't deal with default values at all on iOS. That's not ideal either, because you do need to know about them to compute the cache key. So we should fix that at some point.
