### ISSUE TITLE
update readme to include starwars example for generating code *caveat

### ISSUE THREAD

**Issue by johndpope** [apollographql/apollo-codegen#257]
this would make most sense in the readme.
apollo-codegen generate test/fixtures/starwars/*.graphql --schema test/fixtures/starwars/schema.json --output API.swift

but it throws this error. 
.../test/fixtures/starwars/AnonymousQuery.graphql: Apollo does not support anonymous operations
.../test/fixtures/starwars/ExplicitTypename.graphql: Apollo inserts __typename automatically when needed, please do not include it explicitly
.../test/fixtures/starwars/TypenameAlias.graphql: Apollo needs to be able to insert __typename when needed, please do not use it as an alias
error: Validation of GraphQL query document failed

**Comment by johndpope** [comment]
deleting those files - does correctly spit out API.swift file.

**Comment by martijnwalraven** [comment]
Those files are used as part of the tests, to test validation. So they are meant to result in validation errors.

**Comment by martijnwalraven** [comment]
If you're looking for an example of Swift output, you'll find a number of Star Wars API test queries [in the Apollo iOS project](https://github.com/apollographql/apollo-ios/tree/master/Tests/StarWarsAPI).
