### ISSUE TITLE
TypeScript error on GitHunt-React

### ISSUE THREAD

**Issue by jtmthf** [apollographql/apollo-codegen#26]
I've been messing around and converting the GitHunt-React repo to use TypeScript along with codegen from this module. Really cool stuff, and it almost worked except for one error in the generated Typescript file.

I got an error on FeedEntryFragment due to incorrect extension of RepoInfoFragment.

```typescript
export interface FeedEntryFragment extends VoteButtonsFragment, RepoInfoFragment {
  id: number;
  commentCount: number;
  repository: {
    fullName: string,
    htmlUrl: string,
    owner: {
      avatarUrl: string,
    } | null,
  };
}

export interface RepoInfoFragment {
  createdAt: number;
  repository: {
    description: string | null,
    stargazersCount: number,
    openIssuesCount: number | null,
  };
  postedBy: {
    htmlUrl: string,
    login: string,
  };
}

export interface VoteButtonsFragment {
  score: number;
  vote: {
    voteValue: number,
  };
}
```

Unfortunately typescript can't merge nested interface properties. What seems to be needed is to extract the nested type information into their own interfaces which could then be either merged or extended. I can't think of an exact example right now, but I'll try to put something together

**Comment by jtmthf** [comment]
Just found one solution. When extending an interface, by including all the properties of the sub-property you're extending, the compiler is okay with it. For example FeedEntryFragment can be rewritten as:

```typescript
export interface FeedEntryFragment extends VoteButtonsFragment, RepoInfoFragment {
  id: number;
  commentCount: number;
  repository: {
    description: string | null,
    stargazersCount: number,
    openIssuesCount: number | null,
    fullName: string,
    htmlUrl: string,
    owner: {
      avatarUrl: string,
    } | null,
  };
}
```

**Comment by rricard** [comment]
Hey @jtmthf thanks for the report, I'm sorry to not have responded to this before. What you raised there could actually affect other languages as well so I think it's worth it that we take a long look at it. I think Flow is definitely affected while @martijnwalraven will be able to tell me if swift is affected as well... Once we asserted the issue, we'll try to fix it, or, you can always try to do a contribution. We have contributor's week coming up so we could guide you during that time in your contribution...

**Comment by Ciantic** [comment]
Is this equivalent? 

```
type FeedEntryFragment = {
  id: number;
  commentCount: number;
  repository: {
    fullName: string,
    htmlUrl: string,
    owner: {
      avatarUrl: string,
    } | null,
  };
} & RepoInfoFragment & VoteButtonsFragment

export interface RepoInfoFragment {
  createdAt: number;
  repository: {
    description: string | null,
    stargazersCount: number,
    openIssuesCount: number | null,
  };
  postedBy: {
    htmlUrl: string,
    login: string,
  };
}

export interface VoteButtonsFragment {
  score: number;
  vote: {
    voteValue: number,
  };
}
```

**Comment by lewisf** [comment]
Fixed this by merging selection sets before generating types instead of relying on interface and interface/extends.
