### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by jonaskello** [apollographql/apollo-codegen#264]
I tried apollo-codegen today for the first time. My scenario is that I want to generate typescript types. When going through the readme I found it a bit difficult to understand what the purpose of the operations are. So I propose that a sentence for each operation is added to the readme like this:

* introspect-schema

The purpose of this operation is to convert a graphql schema to a JSON file which can then be used by the "generate" operation.

* generate

The purpose of this operation is to generate types for queries and mutations made against the schema (it will not generate types for the schema itself).

**Comment by jonaskello** [comment]
If the above is correct (which it might not be because I misunderstood something), then I would be happy to make a PR with the above changes.

**Comment by martijnwalraven** [comment]
Thanks for the feedback! I agree we need to improve the docs. We'd eventually like to revise some of these commands and integrate better with other tools, but your basic understanding is correct:

- `introspect-schema` was originally only used to introspect a GraphQL server and download the introspection result (`schema.json`). We then added the ability to use it to convert a local `schema.graphql` into that same JSON representation. As has been mentioned in some issues, it may actually make more sense to allow `schema.graphql` to be used as input directly, so you wouldn't have to use `introspect-schema` for a local schema file.

- `generate` is indeed used to generate types for query and mutation results, as well as types used by these operations, such as enums and input object types. A point of continued confusion is that people expect types to be generated from the schema alone, but that wouldn't give you the type safety you get form operation-specific types.

(`apollo-codegen` was originally written to support Apollo iOS, and I wrote [a blog post about the benefits of operation-specific types](https://dev-blog.apollodata.com/mapping-graphql-types-to-swift-aa85e5693db4) that we may want to link to. But it would be even better to explain this in the context of TypeScript/Flow types.)

A PR to the docs is definitely welcome, and so is any other feedback you may have on how the tool works or should work!

**Comment by jonaskello** [comment]
I think part of the expectation that full schema types will be generated is that the example specifies the output file name as `schema.ts`. Here is the example command in the readme:

```
# TypeScript
apollo-codegen generate **/*.graphql --schema schema.json --target typescript --output schema.ts
```
I think it would clarify a bit if the output file name would be changed to `operation-types.ts` or something similar, instead like this:

```
# TypeScript
apollo-codegen generate **/*.graphql --schema schema.json --target typescript --output operation-types.ts
```

**Comment by martijnwalraven** [comment]
I hadn't noticed that, but that makes sense! Maybe `operation-result-types.ts`?

**Comment by jonaskello** [comment]
I made a PR in #265. Please check if it makes sense :-).

**Comment by jonaskello** [comment]
The PR is merged now so I'm closing this.
