### ISSUE TITLE
gql tag in commented code should be ignored

### ISSUE THREAD

**Issue by jonaskello** [apollographql/apollo-codegen#266]
I have this commented code in index.tsx:

```
// const query = gql`
//   {
//     users {
//       PersonId
//   }
// `;
```

I run this command:

```
$ apollo-codegen generate **/*.tsx --schema schema.json --target typescript --output schema.ts
```

I get this error:
```
.../index.tsx: Syntax Error index.tsx (2:1) Cannot parse the unexpected character "/".

1:
2: //   {
   ^
3: //     users {
```

It seems that apollo-codegen is trying to parse the query even though it is commented.

The behaviour I expect is that apollo-codegen should ignore `gql` tags in commented code.

**Comment by lewisf** [comment]
i think this should be fixed. please check!
