### ISSUE TITLE
Glob pattern to cover both .ts and .tsx files

### ISSUE THREAD

**Issue by jonaskello** [apollographql/apollo-codegen#267]
I'm trying to have apollo-codegen extract queries from both my .ts and .tsx files by using a glob pattern of `'**/*.ts{,x}` like this:

```
$ apollo-codegen generate '**/*.ts{,x}' --schema schema.json --target typescript --output schema.ts
```

I get this error:

```
.../node_modules/apollo-utilities/src/getFromAST.ts: Syntax Error /XXX/node_modules/apollo-utilities/src/getFromAST.ts (1:1) Unexpected )

1: );
   ^
2:   }
```

Not sure if my pattern is wrong or unsupported?

**Comment by jtmthf** [comment]
@jonaskello Unfortunately that is not supported at the moment. Here is what I've been using in my projects.

```sh
apollo-codegen generate $(find src -iname \"*.ts\" -o -iname \"*.tsx\") --target typescript --output src/schema.ts
```

I do agree that Apollo-codegen should natively support globs.

**Comment by jtmthf** [comment]
@jonaskello I may have answered too soon. It appears that globbing is ideally done by your shell, however only ZSH and bash v4+ when configured to do so will do the double-star glob. Even still I had issues getting that working in npm scripts which I assume you're trying to do too.

Here's what I ended up doing. [schnittstabil/globstar](https://github.com/schnittstabil/globstar) is a package that lets you use globstar patterns in npm scripts in a cross-platform manner. Here is what my final command is. Note that double quotes are only required on windows, but I'd rather keep it generic.

```
"globstar --node -- apollo-codegen generate \"src/**/*.ts{,?}\" --target typescript --output src/schema.ts"
```

**Comment by jonaskello** [comment]
The double star seems to work for me out of the box (the examples in the readme also has double stars). It is just the `.ts{,x}` part that is not working. I also tried `**/*.{ts,tsx}` but it did not work either. The `**/*.ts{,x}` does works for me in mocha so I think it is a valid pattern.

**Comment by keplersj** [comment]
I use zsh and have been running the following command without issue:

```
apollo-codegen generate src/**/*.ts src/**/*.tsx --schema schema.json --target typescript --output src/types/schema.ts
```

**Comment by jonaskello** [comment]
Nice workaround 👍 I didn't know that you could specify multiple file names.

If the intention is that you should be able to use glob pattern I think it is still broken, but this workaround is very useful.

**Comment by inakianduaga** [comment]
This definitely works for me when using it as an npm script task inside `package.json`
```json

"scripts": {
    "apollo:codegen": "apollo-codegen generate **/*.{ts,tsx} --schema ...",
}
```

**Comment by jonaskello** [comment]
In the [prettier docs](https://prettier.io/docs/en/cli.html) I found this comment:

> Don't forget the quotes around the globs! The quotes make sure that Prettier expands the globs rather than your shell, for cross-platform usage. The glob syntax from the glob module is used.

Seems like they use `"` rahter than `'`. May be relevant here too since codegen also uses the glob package AFAIK. I'll close this for now until I have a chance to test that theory.
