### ISSUE TITLE
error: No introspection query result data found, server responded with: {"message":"no API found with those values"} when using API gateway

### ISSUE THREAD

**Issue by AlphaGao1993** [apollographql/apollo-codegen#271]
we are using api gateway but now we can't get the schema.json from any server, not only original server,but also api-gateway server.

**Comment by martijnwalraven** [comment]
Make sure you're using the right URL and setting any authentication headers required. This is not specific to `apollo-codegen`, all it does is send an introspection query to the endpoint. You may want to try if you can access the endpoint through `curl` or GraphiQL to make sure it's working.

**Comment by AlphaGao1993** [comment]
thank you and I find right url to request.
