### ISSUE TITLE
API.swift implementation: recurring errors on type conversion in Swift 3.0 (Xcode_Version 9.0 (9A235)

### ISSUE THREAD

**Issue by modond** [apollographql/apollo-codegen#274]
These are recurring fail to build error message in Swift 3.0.. 
graphcool backend
(all queries and mutations in the project have been tested in graphcool  playground to the graphql schema and are behaving as expected.. )

building the API.swift file generates recurring errors with regards to some type conversions, these are Xcode comments and the generated code they are referring to:

Cannot convert value of type '[GraphQLSelection]' to expected argument type 'GraphQLSelectionSet.Type'

`GraphQLField("fieldName", type: .object(FieldName.selections))`

Use of unresolved identifier GraphQLVariable

`
    public struct CreateSession: GraphQLSelectionSet {
      public static let possibleTypes = ["Session"]

      public static let selections: [GraphQLSelection] = [
        GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
        GraphQLField("id", type: .nonNull(.scalar(GraphQLID.self))),
        GraphQLField("createdAt", type: .nonNull(.scalar(String.self))),
        GraphQLField("cfdState", type: .scalar(CfdState.self)),
        GraphQLField("dodState", type: .scalar(DodState.self)),
        GraphQLField("rodState", type: .scalar(RodState.self)),
        GraphQLField("ppState", type: .scalar(PpState.self)),
        GraphQLField("sosState", type: .scalar(SosLocationState.self)),
        GraphQLField("dodState", type: .scalar(DodState.self)),
        GraphQLField("pp", type: .object(Pp.selections)),
      ]

      public var snapshot: Snapshot

      public init(snapshot: Snapshot) {
        self.snapshot = snapshot
      }`

Binary operator '+=' cannot be applied to two 'Snapshot' (aka 'Dictionary<String, Optional<Any>>') operands

      public struct Fragments {
        public var snapshot: Snapshot

        public var userDetails: UserDetails {
          get {
            return UserDetails(snapshot: snapshot)
          }
          set {
            snapshot += newValue.snapshot
          }
        }
      }
    }`

**Comment by martijnwalraven** [comment]
What versions of Apollo iOS and `apollo-codegen` are you running? These all look like conflicts between the generated code and the framework code.

**Comment by modond** [comment]
I am using apollo-codegen 0.17.0-alpha.12 and swift 3.2. 
Is there a way (some list available) to check if you are using the right framework version with the right swift version? thank you!

**Comment by martijnwalraven** [comment]
This is not about the Swift version, but the Apollo iOS version. The Apollo iOS framework comes with a `check-and-run-apollo-codegen.sh` script that we recommend you use to run `apollo-codegen`, to make sure you're generating compatible code. It will also install or update `apollo-codegen` for you. Have you followed the instructions in the docs [to add a codegen build step](http://dev.apollodata.com/ios/installation.html#adding-build-step)?

**Comment by modond** [comment]
I checked that and I do have that build step (just before compile sources) added. 
I took it out and put it in again.. restarted.. 
Probably it is a version problem as I got this as shell script invocation error

`Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure`

Again I got the same type conversion errors.

**Comment by martijnwalraven** [comment]
@modond Any other output from the build step (you may have to expand the logs)? Can you check which version of Apollo iOS you're running? It seems like you're running a version that's older than the `apollo-codegen` version you have installed.

**Comment by modond** [comment]
![schermafbeelding 2017-10-17 om 10 51 09](https://user-images.githubusercontent.com/1257368/31655445-2e071fc2-b329-11e7-9237-ff65bedb391c.png)


Did I understand your question? this is the info.plist

**Comment by martijnwalraven** [comment]
No, I mean the version of the Apollo iOS framework. Do you install the framework through Cocoapods, Carthage, or manually?

**Comment by martijnwalraven** [comment]
You can find the currently installed version in `Podfile.lock`, and you can update to the latest version by running `pod update Apollo`.

**Comment by modond** [comment]
aha..  this is podfile.lock
- Apollo (0.6.5):
- Apollo/Core (= 0.6.5)

after the update I get `Using Apollo (0.6.5)`
So that seems to be the same version..

**Comment by martijnwalraven** [comment]
I'm not sure how you'd end up with `apollo-codegen` 0.17.0-alpha.12 if you're running Apollo iOS 0.6.5. Could you uninstall `apollo-codegen`(`npm uninstall apollo-codegen -g`), remove `API.swift`, and try rebuilding? 

I'm releasing Apollo iOS 0.7.0 right now, so after that `pod update` should give you the latest version. But I want to make sure your build script will also be able to update `apollo-codegen` to the latest version.

**Comment by modond** [comment]
I uninstalled, and reinstalled -g. I removed `AP.swift` ran the update `pod update,` this gives me Apollo 0.7.0 (was 0.6.5). Then I ran `apollo-codegen generate **/*.graphql --schema schema.json -- output API.swift` And I got the following:

`Error: ENOENT: no such file or directory, open '/Users/moniquehaas/Desktop/CognitoUsersForDelivrsGraphQL-aws-my-sample-app-ios-swift/MySampleApp/MySampleApp/**/*.graphql'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at inputPaths.map.inputPath (/usr/local/lib/node_modules/apollo-codegen/src/loading.ts:69:21)
    at Array.map (native)
    at Object.loadAndMergeQueryDocuments (/usr/local/lib/node_modules/apollo-codegen/src/loading.ts:68:30)
    at Object.generate (/usr/local/lib/node_modules/apollo-codegen/src/generate.ts:31:20)
    at Object.yargs.command.command.command.argv [as handler] (/usr/local/lib/node_modules/apollo-codegen/src/cli.js:191:7)
    at Object.self.runCommand (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:927:19)`

I did get the `API.swift` I then restarted the project ..and rebuild it..
`Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure`

**Comment by martijnwalraven** [comment]
There seems to be an extra space between `-- ` and `output`.

But you shouldn't have to run `apollo-codegen` manually, that is what the build step is for. If you do this manually, you won't get the version check. It may work now, but you'll run into the same issues with future updates. So I still think we should debug your build step. Can you expand the output to see if there are any errors?

**Comment by modond** [comment]
I added to my comment above. As well I deleted the manually inserted API.swift from the project (because of your remark) and rebuild. I do get a new empty schema.json file but I cannot find the API.swift file in the project..

**Comment by martijnwalraven** [comment]
You shouldn't remove `API.swift` from your project. You can delete the file from disk without removing it from the project. Not sure why your `schema.json` would be empty, but you can always recreate it b running `apollo-codegen introspect-schema` against your API.

**Comment by modond** [comment]
I then put in my schema.json (not empty) just by copying it over from the project directory. And rebuild to see if that would deliver a API.swift file

**Comment by martijnwalraven** [comment]
The build step should create `API.swift`, but it won't add it to your project. So you will still have to add it manually (but you'll only have to do that once).

**Comment by modond** [comment]
Dit that, and it now seems to work fine, nog more type conversion errors. I still get an error warning on a shell script `Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure` but I think it refers to another script ( I am also having some file construction issues with AWS boilerplate code..) Thank you soo much for your patience and your endurance! I learned a lot along the way on how apollo-codegen operates.

**Comment by martijnwalraven** [comment]
Great, glad that worked!
