### ISSUE TITLE
`operation-ids-path` option is broken (Swift)

### ISSUE THREAD

**Issue by kompfner** [apollographql/apollo-codegen#280]
When passed in an `--operation-ids-path`, `apollo-codegen` should generate a file mapping between operation ids and operation sources (including dependent fragments). This functionality was added as part of https://github.com/apollographql/apollo-codegen/pull/147.

This functionality is now broken. Running `apollo-codegen` with the `--operation-ids-path` argument yields `TypeError: path must be a string or Buffer`.

There are two problems, as far as I can tell. In `writeOperationIdsMap` in `generate.ts`:
1. `context` no longer contains `operationIdsPath`
2. Each operation in `context.operations` no longer contains `operationId` or `sourceWithFragments`

My guess is that this broke as a result of the changes in https://github.com/apollographql/apollo-codegen/pull/228.

**Comment by martijnwalraven** [comment]
I'm sorry the compiler rewrite broke the `--operation-ids-path` feature, but since you are the only one using it, and you know what is needed, could you open a PR to fix this?

**Comment by inakianduaga** [comment]
I can confirm this is still broken

**Comment by JustinDSN** [comment]
I put up a PR to address this issue.
