### ISSUE TITLE
Add support for unknown enum values

### ISSUE THREAD

**Issue by abhisood** [apollographql/apollo-codegen#284]
**Problem**: whenever server returns new unsupported by client enum value it's a breaking change, as we force cast the raw string value to appropriate generated enum constant.

Simillar to apollographql/apollo-android#712 on Android
iOS issue: https://github.com/apollographql/apollo-ios/issues/174

**Comment by JustinDSN** [comment]
@abhisood this should be addressed by #290.  Can you take a look and let us know?
