### ISSUE TITLE
Jump statements in “finally” block

### ISSUE THREAD

**Issue by mangeles13** [apollographql/apollo-codegen#295]
**Issue**
Jump statements performed at a “finally” block of a try-catch-finally code may cause unexpected state for the app as it prevents proper clean-up / wrap-up. This may also cause crashes to the app as normal exception handling flow is interrupted.

**Files**
-  **/node_modules/apollo-codegen/lib/compilation.js**
- **/node_modules/apollo-codegen/lib/cli.js**
- **/node_modules/apollo-codegen/lib/errors.js**
- **/node_modules/apollo-codegen/lib/errors.js**

**Recommendation**
Handle exceptions in the “catch” portion of the try-catch-finally code. If that is not possible throw the exception on the “catch” portion, but have the calling function handle it.

**Comment by lewisf** [comment]
i don't think we have any try-catch-finally code that is offending. it looks like it might be a typescript compiler thing. going to close this out as we don't have control over that.

If you think this is still an issue, feel free to re-open, thanks!
