### ISSUE TITLE
Adding unknown num types despite not being in schema

### ISSUE THREAD

**Issue by helloniklas** [apollographql/apollo-codegen#297]
So the masters version v0.17.2 has started to add a unknown enum types from the schema into the API.swift. Reverting to v0.17.1 and it works fine again.

**Comment by martijnwalraven** [comment]
This was added as a feature, but we're currently rethinking our approach. Please join the discussion on [the related PR for Apollo iOS](https://github.com/apollographql/apollo-codegen/pull/290).
