### ISSUE TITLE
Apollo Codegen is opiniated on how I design my Graph / Queries

### ISSUE THREAD

**Issue by chollier** [apollographql/apollo-codegen#298]
Hi! First thanks for the awesome work!! 👌🏼

Here is my use case:

Schema:
```graphql
type Query {
  friendsFromSchool: FriendsConnection!
  friendsFromWork: FriendsConnection!
}
```
Query:
```graphql
query FriendsQuery(
  $isWorkSection: Boolean!
  $isSchoolSection: Boolean!
) {
  ...FriendsFromSchoolFragment @include(if: $isSchoolSection)
  ...FriendsFromWorkFragment @include(if: $isWorkSection)
}

fragment FriendsFromSchoolFragment on Query {
  friends: friendsFromSchool {
    edges {
      cursor
    }
  }
}

fragment FriendsFromWorkFragment on Query {
  friends: friendsFromWork {
    edges {
      cursor
    }
  }
}
```

as query variables I would pass, depending on the section I'm browsing:
```json
{
  "isWorkSection": false,
  "isSchoolSection": true
}
```

now if I run `apollo-codegen`, I would get:
```
.../js/components/hocs/withGraphqlFilters.graphql: Fields "friends" conflict because friendsFromSchool and friendsFromWork are different fields. Use different aliases on the fields to fetch both if this was intentional.
.../js/components/hocs/withGraphqlFilters.graphql: Fields "friends" conflict because friendsFromSchool and friendsFromWork are different fields. Use different aliases on the fields to fetch both if this was intentional.
```

while I get that it might be cumbersome to generate types if the selections were not the same, since the returned types are the same shouldn't this be ok?

**Comment by martijnwalraven** [comment]
The error you're seeing is a validation error generated by `graphql-js`, not something `apollo-codegen` specific. If you try to execute the query, the server should reject it with the same error.

`friends: friendsFromSchool { ... }` and `friends: friendsFromWork { ... }` cannot be merged because they are different fields. If you want to fetch both in one query, you should remove the aliases. If you want to get either one or the other as `friends`, you should use separate queries.

**Comment by chollier** [comment]
Ah interesting, thanks for the precision @martijnwalraven. Well the query doesn't get rejected with `graphql-ruby` and just works™
It's convenient for me to always use the alias but I guess I'll have to change that.

**Comment by martijnwalraven** [comment]
Ah, that seems like an issue you should report to `graphql-ruby`, because as far as I can see it violates the spec.
