### ISSUE TITLE
Error while generating the ts file

### ISSUE THREAD

**Issue by mrdezzods** [apollographql/apollo-codegen#300]
When I run the command to generate a typescript defination for `ts` files with `gql` tag, I get the error below.

```bash
.../apollo-cache/src/types/DataProxy.ts: Syntax Error /Users/myapp/node_modules/apollo-cache/src/types/DataProxy.ts (1:2) Unexpected Name "template"

1:  template
    ^
2:      * string tag from

```

The command that I used is:
```bash
apollo-codegen generate **/*.ts  --target typescript --schema schema.json --output Schema.d.ts
```

**Comment by lewisf** [comment]
try making sure `node_modules` isn't part of your glob pattern to see if that solvers your problem @mrdezzods. If it does, we may be able to ignore node_modules by default in the future.

**Comment by lewisf** [comment]
Closing this otherwise, @mrdezzods let me know if that recommendation didn't solve your problem.
