### ISSUE TITLE
Can't generate code

### ISSUE THREAD

**Issue by andrew-w-ross** [apollographql/apollo-codegen#301]
First time trying out this package and I can't seem to get it to work.

Given the following file `schema.graphql`

```graphql
type Person{
  id : ID!
  firstName : String!
  surName : String!
  age : Int
}

type Query {
  me : Person!
}
```

I generate the `schema.json` dump with `apollo-codegen introspect-schema schema.graphql --output schema.json`.

Then I try and create some types with :
`apollo-codegen generate --schema schema.json --target typescript --output operation-result-types.ts`

And I also tried : 
`apollo-codegen generate schema.graphql --schema schema.json --target typescript --output operation-result-types.ts`

The output for both is 
```typescript
/* tslint:disable */
//  This file was automatically generated and should not be edited.

```
Neither command fails but it doesn't seem to produce anything but a semi empty file. What am I doing wrong?

**Comment by martijnwalraven** [comment]
`apollo-codegen` generates query-specific types, so you'll need to provide `.graphql` files with queries as input.

**Comment by andrew-w-ross** [comment]
As you can see I did that on the second attempt at generating. Or do I have to pass that in differently?

**Comment by martijnwalraven** [comment]
I don't mean the schema, but files with actual queries. So if you have a file called `MyName.graphql` with contents like:

```graphql
query MyName {
  me {
    firstName
    lastName
  }
}
```

You would run a command like:

```sh
apollo-codegen generate MyName.graphql --schema schema.json --target typescript --output operation-result-types.ts
```

**Comment by andrew-w-ross** [comment]
@martijnwalraven Ah I see so your limited to the query specifically. I was trying to generate an types describing my schema. Thanks for your help.
