### ISSUE TITLE
Splitting complex types into subtypes

### ISSUE THREAD

**Issue by rasdaniil** [apollographql/apollo-codegen#302]
Hi 
I wan't to inquire if there are any plan on this issue. Say you have your gql:
```
      dishes {

        ... on RecipeDish {
          id
          recipeId
        }

        ... on IngredientDish {
          id
          ingredient 
        }
      }
```

The generated type would be then
```
export type MenuDishFragmentFragment = {
  dishes:  Array<( {
      __typename: "RecipeDish",
      id: string,
      recipeId: string,
    } | {
      __typename: "IngredientDish",
      id: string,
      ingredient:  {
        productId: string,
      },
    }
  ) >,
};
```

Now dealing with entities in code I cannot say `let newDish: MenuDishFragment.RecipeDish;` or similar but by copying types from the generated file into my code manually

Are there ways to deal with the problem?

**Comment by martijnwalraven** [comment]
If I understand you correctly, I think https://github.com/apollographql/apollo-codegen/issues/159 would solve your issue.

**Comment by lewisf** [comment]
Closing this since you can get exactly this by using the new `flow-modern` target, which will soon be the default `flow` target in releases.

Going to close this otherwise -- implementing this in the older target was actually really messy and difficult to understand/iterate on.
