### ISSUE TITLE
Schema field names using swift keywords causes compile time error

### ISSUE THREAD

**Issue by tonythebully** [apollographql/apollo-codegen#303]
As from title, having a field name called operator generates the following code within the api file:
```
      public var operator: LogicalOperator {
        get {
          return snapshot["operator"]! as! LogicalOperator
        }
        set {
          snapshot.updateValue(newValue, forKey: "operator")
        }
      }
```
where the var `operator` would get an error.

While i am aware that doing \` escapes it, would codegen be able to recognise keywords and escape them automatically?

**Comment by martijnwalraven** [comment]
`apollo-codegen` already escapes reserved keywords: https://github.com/apollographql/apollo-codegen/blob/bb604db1531a50d5f55235e8a56e73ddf325b8a5/src/swift/language.ts#L34-L53
But I guess we missed 'operator', so a PR is welcome!

**Comment by tonythebully** [comment]
I can see operator as part of the list of words already, but it's not escaping in my codegen?

**Comment by martijnwalraven** [comment]
Ah, it seems this was fixed in 0.17.1: https://github.com/apollographql/apollo-codegen/commit/51bf4bf15376687f1922b0111cd0bc286bbe7e82

**Comment by tonythebully** [comment]
I just did an update to the latest codegen, but I'm getting an issue:
```
public var rawValue: RawValue {
    switch self {
      case .present: return "present"
      case .away: return "away"
      case .unknown: return "unknown"
      case .unknown(let value): return value
    }
  }
```
where the second unknown case has an error saying `Invalid redeclaration of 'unknown`
perhaps this deserves a seperate issue

**Comment by martijnwalraven** [comment]
Yes, there is a discussion about this on https://github.com/apollographql/apollo-codegen/pull/290.
