### ISSUE TITLE
Add support of subscription

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-codegen#316]
Android client is going to start working on GraphQL subscription support, and it requires to include subscription generation.

Here is the example of subscription operation taken from GitHunt API
```
subscription Test {
  commentAdded(repoFullName: "javaScript") {
    id
    content
  }
}
```

**Comment by lewisf** [comment]
@martijnwalraven do we have someone better suited to making changes to support apollo-android?

if not, if I get some context I might be able to tackle this

**Comment by martijnwalraven** [comment]
It turns out this was already supported!
