### ISSUE TITLE
Can't initialize variable what type is String

### ISSUE THREAD

**Issue by rnitame** [apollographql/apollo-codegen#317]
On server (use apollo-server-koa)

```js
input xxxInput {
  parser: String = "simple"
}
```

On client (use apollo-android)

```java
    private @Nullable String parser = simple;
```

It happens an error because it is not enclosed in double quotes :(
Maybe this repository is irrelevant, so please tell me then

**Comment by martijnwalraven** [comment]
Most of the Apollo Android codegen lives in https://github.com/apollographql/apollo-android, so it would be best to open an issue there instead.
