### ISSUE TITLE
Flow Modern does not export "input" types

### ISSUE THREAD

**Issue by erydo** [apollographql/apollo-codegen#320]
https://github.com/apollographql/apollo-codegen/blob/8c46ca32e6971884a716f4973c5539745f8f3115/src/javascript/flow/__tests__/__snapshots__/codeGeneration.ts.snap#L815-L820

These should be annotated like `export type ReviewInput`

**Comment by lewisf** [comment]
this should be as easy as changing the ast that makes up this node to be wrapped with an export statement. was an oversight on my part.

accepting PR's for this! otherwise i can try to get to it the next time i get time to work on this

**Comment by lewisf** [comment]
Fixed in #340 @martijnwalraven let's schedule a release!
