### ISSUE TITLE
Windows: apollo-codegen generate does not work.

### ISSUE THREAD

**Issue by arondesign** [apollographql/apollo-codegen#34]
I've tested on Mac, Windows, and Bash on Ubuntu on Windows. It works great on Mac and Windows Bash, but when I run in a command prompt or powershell:

`apollo-codegen generate src/**/*.graphql --schema graphql.schema.json --target typescript --output src/schema.d.ts`

I get errors like the following:

`Error: ENOENT: no such file or directory, open 'C:\Projects\src\**\*.graphql'`

It's interpreting the wildcard path as a string

**Comment by stubailo** [comment]
> src/**/*.graphql

That's a bash/linux shell glob feature. I think it actually expands into a list of files before it even gets to the `apollo-codegen` script. Can you check if it works if you pass just one filename in that location?

**Comment by arondesign** [comment]
It works if I just pass in 1 filename. I noticed 'glob' is included as an npm dependency but not being used anywhere.

When I use the glob pattern with [graphql-document-collector](https://github.com/apollostack/graphql-document-collector), which uses 'glob' from npm, it works fine.

**Comment by stubailo** [comment]
Yeah, that one doesn't rely on the bash glob. Is there a way in cmd on windows to select multiple files? It seems silly to build in a feature into this library that exists already in some shells.

**Comment by arondesign** [comment]
Haha yea, I hear ya, there isn't really unfortunately (at least that I know of). The solution is supposed to be windows ubuntu bash, but that has it's own issues with file watchers that won't be patched for another 1-3 months.
