### ISSUE TITLE
error: Validation of GraphQL query document failed

### ISSUE THREAD

**Issue by listepo-alterpost** [apollographql/apollo-codegen#344]
- `npm install -g apollo-codegen`
- [schema.graphql](https://gist.github.com/HideDev/0efa7aa08f437c52f738cca1efabfe51)
- `apollo-codegen introspect-schema schema.graphql --output schema.json`
- `apollo-codegen generate **/*.graphql --schema schema.json --target typescript --output operation-result-types.ts`

```
.../ivan/github/demo/schema.graphql: The Comment definition is not executable.
.../ivan/github/demo/schema.graphql: The ContentFormatEnum definition is not executable.
.../ivan/github/demo/schema.graphql: The Email definition is not executable.
.../ivan/github/demo/schema.graphql: The ImageSizeEnum definition is not executable.
.../ivan/github/demo/schema.graphql: The ImageType definition is not executable.
.../ivan/github/demo/schema.graphql: The ImageTypeEnum definition is not executable.
.../ivan/github/demo/schema.graphql: The Node definition is not executable.
.../ivan/github/demo/schema.graphql: The Query definition is not executable.
.../ivan/github/demo/schema.graphql: The SearchResultType definition is not executable.
.../ivan/github/demo/schema.graphql: The Story definition is not executable.
.../ivan/github/demo/schema.graphql: The StoryAffordancesEnum definition is not executable.
.../ivan/github/demo/schema.graphql: The Url definition is not executable.
.../ivan/github/demo/schema.graphql: The User definition is not executable.
error: Validation of GraphQL query document failed
```

**Comment by triedal** [comment]
I'm seeing this issue as well.

**Comment by martijnwalraven** [comment]
You have to make sure that `schema.graphql` is not part of the files that are treated as query documents. With `**/*.graphql`, all `.graphql` files will be selected, so you should probably make that more specific and/or move the schema file.

**Comment by triedal** [comment]
Woops. I didn't pay enough attention to the OP's errors. I'm seeing the following:

```.../src/graphql/types/user.graphql: The UserType definition is not executable.
.../src/graphql/types/user.graphql: The Query definition is not executable.
.../src/graphql/types/user.graphql: The Mutation definition is not executable.
.../src/graphql/types/user.graphql: The User definition is not executable.
```
Here is the user.graphql file:

```
enum UserType {
  ISA,
  REA,
  ADMIN
}

type Query {
  currentUser: User
}

type Mutation {
  login(email: String!, password: String!): User
}

type User {
  _id: ID
  email: String
  type: UserType
  jwt: String
}
```

Do you see anything I'm doing wrong?

Command ran: `apollo-codegen generate src/**/*.graphql --schema src/data/schema.json --target typescript --output operation-result-types.ts`

**Comment by sventschui** [comment]
@triedal It‘s the same error as the OP has. Make sure you do not include your schema file (user.graphql) into the apollo-codegen glob

**Comment by alonstar** [comment]
I have the same issue, too.

1. npm install -g apollo-codegen
2. apollo-codegen introspect-schema http://localhost:13083/graphql --output schema.json
3. get-graphql-schema http://localhost:13083/graphql > schema.graphql
4. apollo-codegen generate schema.graphql --schema schema.json --target typescript --output operation-result-types.ts

I used https://github.com/graphcool/get-graphql-schema to download schema.graphql
I only have two files in directory : schema.graphql and schema.json

Did I do anything wrong?


	λ apollo-codegen generate schema.graphql --schema schema.json --target typescript --output operation-result-types.ts
	.../GraphQL Spec\schema.graphql: The schema definition is not executable.
	.../GraphQL Spec\schema.graphql: The AllBeneficiaryResult definition is not executable.
	.../GraphQL Spec\schema.graphql: The AllTradeOrderResult definition is not executable.
	.../GraphQL Spec\schema.graphql: The AssessmentAnswerOption definition is not executable.

**Comment by Charius** [comment]
facing the same issue as @alonstar introduced... Can someone clarify the way of using codegen, please?

**Comment by Charius** [comment]
@martijnwalraven thanks for the info about `gql` tags, I'll try it out.

**Comment by alonstar** [comment]
@martijnwalraven : my graphql server is working , how do I check my schema.graphl is correct ? thanks for your help.

**Comment by listepo** [comment]
@martijnwalraven `apollo-codegen generate schema.graphql --schema schema.json --target typescript --output operation-result-types.ts` also does not work. https://github.com/graphql/graphql-js/blob/5fe39262a308df944a87cc85b225228e7556aaa4/src/validation/rules/ExecutableDefinitions.js#L22

**Comment by martijnwalraven** [comment]
@listepo The input to `apollo-codegen` should be query documents, not the schema (that is specified using `--schema`).

**Comment by franxois** [comment]
Thanks, so just to be clear, we can't use apollo-codegen to extract typescript types from a backend schema.graphql. It is only use with query document, is that right ?

**Comment by martijnwalraven** [comment]
You use both a schema and query documents, but the generated types are query-specific (so they accurately type the results returned from the server).

**Comment by ntziolis** [comment]
Not sure if anybody else is here because of this but there are app frameworks like graphcool that let you have graphql files in your project that are either queries or extension to the schema. If you structure your project by functionality you will have a mixture of both in the same folder. This means the usual way of distinguishing between schema or query by path dosen't work

The way we worked around this was to simply be more specific via the file extension, using `*.schema.graphql` and `*.query.graphql`.
This allows us to have separate apolllo scripts for schema and query files. and have just 3 scripts doing all the work:
- generate types from schema
- generate types from queries (graphql)
- generate types from queries (gql)

**Comment by sventschui** [comment]
@MiguelSavignano you don't need your `getCategory.graphql` as `apollo-codegen` can extract your graphql query from your JS source. 

Maybe it won't work in your case as you are using a `${id}` expression instead of passing the variables to `client.query`. Try it like this:

```  
  client.query({
    query: gql` query Q($id: Int!) {
      category(id: $id) {
        name
      }
    }`, 
    variables: { id }
  }): Promise<{
    data: getCategoryQuery;
  }>
```

**Comment by pleerock** [comment]
Anyone found a resolution for this issue? I have a `Post.graph`:

```ts
type Post {
    id: Int!
    name: String!
    text: String
}
```

And I have an error when I run:

```
$ apollo-codegen generate Post.graphql --schema schema.json --target typescript --output operation-result-types.ts
.../www/yakdu/node.yakdu.dev/Post.graphql: The Post definition is not executable.
error: Validation of GraphQL query document failed
```

**Comment by sventschui** [comment]
@pleerock your Post.graph is supposed to contain a query against the schema in schema.json. e.g.

```
query MyPostQuery {
  post {
    id
    name
  }
```

**Comment by dobesv** [comment]
I think the confusion here is that some people (myself included) want typescript interfaces for all the types in the graphql schema, not just for the query and mutation operations used by the client.  That way we can use generated types on the server-side to add types to our resolvers.  Not sure if there is a tool out there that does this?

**Comment by listepo-alterpost** [comment]
@dobesv you're right https://github.com/apollographql/apollo-codegen/issues/351

**Comment by ibigpapa** [comment]
I found that i was using what apollo considers anonymous operation.  Which i fixed by adding a name to the query.

Before
```
query {
  example {
    id
  }
}
```
After
```
query Example{
  example {
    id
  }
}
```

**Comment by constconsole** [comment]
graphql-schema-typescritp is a good lib for generating types, also there is gql2ts to convert a graphql schema to a typescript definition

**Comment by nemethmik** [comment]
@ibigpapa This was a shocking experience, I've just wasted three hours of my life until I found your hint. Would it be possible to improve the error message "Validation of GraphQL query document failed" to give some hints about the problem.

**Comment by AlexCppns** [comment]
Looks like codegen doesn't do what I thought it would...

**Comment by lawloretienne** [comment]
In my case i need to update the query `.graphql` file as well as the `schema.json`

**Comment by ivorpad** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget accumsan tellus, et condimentum felis. Quisque elit ante, euismod id congue vel, dapibus tempor dolor. Nullam cursus mauris sed hendrerit placerat.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget accumsan tellus, et condimentum felis. Quisque elit ante, euismod id congue vel, dapibus tempor dolor. Nullam cursus mauris sed hendrerit placerat.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget accumsan tellus, et condimentum felis. Quisque elit ante, euismod id congue vel, dapibus tempor dolor. Nullam cursus mauris sed hendrerit placerat.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget accumsan tellus, et condimentum felis. Quisque elit ante, euismod id congue vel, dapibus tempor dolor. Nullam cursus mauris sed hendrerit placerat.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget accumsan tellus, et condimentum felis. Quisque elit ante, euismod id congue vel, dapibus tempor dolor. Nullam cursus mauris sed hendrerit placerat.

**Comment by TSMMark** [comment]
Is it possible to have `apollo client:codegen` exit with non-zero status when `Validation of GraphQL query document failed`? 

I can't find this anywhere. Maybe a flag could be added such as: `--fail-on-warning` or `--error-level=warning`
