### ISSUE TITLE
Swift codegen creates duplicate enum values for Unknown 

### ISSUE THREAD

**Issue by annjose** [apollographql/apollo-codegen#365]
Our codegen is failing since version 0.17 onwards (in which the PR #290 in Swift to support `unknown` enums was added). The reason why it fails it that `UNKNOWN` is a valid property in our schema (see example below) and this conflicts with the `unknown` case that was auto-generated by apollo-codegen. So the generated code with have two enum values - one from the schema and the other with associated value added by codegen.

Our schema defines this value for many enums and these values have been in use for quite some time. I guess this will be an issue for other schemas as well since Unknown is a very common property. So before we fork the repo to fix this in the codegen, I was wondering if there is a generic solution that will avoid this name-conflict (for example, use a name that has lower chances of conflict). If there are any ideas of how to resolve this, I am willing to submit a PR.

Sample snippet from our schema that contains `UNKNOWN` as a valid enum value:
```
{
    "possibleTypes": null,
    "description": null,
    "name": "Common_AddressDeliverableStatusEnumInput",
    "interfaces": null,
    "enumValues": [
        {
            "isDeprecated": false,
            "deprecationReason": null,
            "description": "DELIVERABLE",
            "name": "DELIVERABLE"
        },
        {
            "isDeprecated": false,
            "deprecationReason": null,
            "description": "NON_DELIVERABLE",
            "name": "NON_DELIVERABLE"
        },
        {
            "isDeprecated": false,
            "deprecationReason": null,
            "description": "UNKNOWN",
            "name": "UNKNOWN"
        }
    ],
    "inputFields": null,
    "kind": "ENUM",
    "fields": null
}
```

**Comment by matvdg** [comment]
We also face the same issue. Before changing our schema (it will be tricky because it's already used in production) we asked ourselves if there is any way to change the name of the "UNKNOWN" enum value that codegen generates for ios ?

**Comment by martijnwalraven** [comment]
Not right now, but it's clear we need to change the current behavior. @MrAlek has been looking into this, and we also want to make sure our solution is aligned with [this Swift evolution proposal for non-exhaustive enums](https://github.com/apple/swift-evolution/blob/master/proposals/0192-non-exhaustive-enums.md).

As a temporary solution, maybe we should just rename it to something like `__UNKNOWN` for now.

**Comment by annjose** [comment]
@martijnwalraven - were you suggesting that we rename to `__UNKNOWN` in our schema? Or were you suggesting that it can be done in the codegen as a temp fix until the Swift 5 evolution proposal is released? (Here is how I am thinking of fixing it in the codegen - https://github.com/annjose/apollo-codegen/pull/1)

**Comment by martijnwalraven** [comment]
@annjose Yes, renaming the generated enum case is what I was suggesting, similar to your solution. 

@MrAlek is on vacation until next week, so let's find a permanent solution after he gets back.

**Comment by annjose** [comment]
@martijnwalraven - Could you reconsider this issue in the light of the fact that `Unknown` is not a reserved keyword or value as per the GraphQL standard? A schema with an enum value 'Unknown' is completely valid and conforms to GraphQL spec. It is just that the code-gen auto-generated an enum with the same value and hence conflicts with the schema-provided value. I believe other teams would also be in the same situation. So wouldn't it better to modify the default codegen to make the auto-generated value to be unique or namespaced (to Apollo) than asking the clients to modify a valid schema which has far-reaching implications?

Of course we have the option of forking the codegen repo and changing it in-house and we are willing to do it for situations where our schema is deviating from the GraphQL spec. But in this situation where the schema is valid, maintaining a fork seems to be unnecessary / work-around. So could you consider resolving the root cause of this issue in the codegen itself?

**Comment by MrAlek** [comment]
I think we should go with `__unknown` too. It looks like the Swift proposal will go with a similar syntax for non-exhaustive enums.

**Comment by martijnwalraven** [comment]
This should be fixed in `apollo-codegen` 0.18.8.

**Comment by martijnwalraven** [comment]
@annjose Sorry this took a while. It was definitely not my intention to suggest this was something you we didn't want to fix in codegen. I just wanted to get Alek's opinion first, because he has been thinking about an alternative to this.

**Comment by MrAlek** [comment]
@martijnwalraven Sorry I didn’t get back on this earlier either. That Swift proposal changed things as it seemed inevitable that a unknown/future syntax would be introduced right inside the enum type rather than some kind of wrapper type like Optional.

**Comment by annjose** [comment]
Thank you @martijnwalraven @MrAlek. I tested with 0.18.8 and the generated code compiles without any errors / tweaks 👍. 
PS: No worries about the delayed response at all; we are really glad that we have a solid solution now. Thanks again for your support.
