### ISSUE TITLE
--add-typename not working when generating files (typescript)

### ISSUE THREAD

**Issue by maierson** [apollographql/apollo-codegen#367]
When generating schema.ts the `--add-typename` argument is not recognized.

From `apollo-codegen generate --help`
```
--add-typename                           For non-swift targets, always add the
                                           __typename GraphQL introspection type
                                           when generating target types
                                                                [default: false]
```
Generate command:

```
apollo-codegen generate app/**/*.graphql --schema schema.json --target ts --output app/schema.ts --add-typename
```
Intended outcome: generates the interfaces with the `__typename` prop present on each one.

Actual outcome: Fails with output:

```
Unknown argument: add-typename
```

Same result with `--addTypename`.  Everything works ok without `--add-typename`.

How to reproduce: Run the generate command with the `--add-typename` argument.

**Comment by bmayen** [comment]
Looks like this is working in latest release

**Comment by shadaj** [comment]
Closing as this has been fixed.
