### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by jacobwgillespie** [apollographql/apollo-codegen#376]
Would it be possible to release a new version to npm?  I would really love access to some of the new `flow-modern` features like #348, but it appears they aren't yet published.

**Comment by lewisf** [comment]
cc @martijnwalraven can we schedule one last release before freezing for the lerna work to land?

**Comment by martijnwalraven** [comment]
I just released 0.18.4 to npm.

**Comment by detrohutt** [comment]
This issue can be closed
