### ISSUE TITLE
Documentation of `modern` targets

### ISSUE THREAD

**Issue by bmayen** [apollographql/apollo-codegen#379]
It's not immediately clear what the intent and differences are between the standard targets and their "-modern" equivalents. Some high-level documentation here would be very useful.

In the meantime, could someone clarify below?

**Comment by martijnwalraven** [comment]
The modern targets are meant to replace the old ones. @lewisf has more details on the differences. He is also working on [a PR](https://github.com/apollographql/apollo-codegen/pull/372) that will make the modern targets the default and remove the old ones.

**Comment by bmayen** [comment]
heh, yeah, I assumed the "modern" targets are the successors :) I guess my question is more along the lines of "what should we expect to change when updating to the new targets?" For instance, I see that they now create `__generated__` folders and `--output` is ignored. Is that all?
