### ISSUE TITLE
Output JSDoc for field descriptions in TypeScript

### ISSUE THREAD

**Issue by prencher** [apollographql/apollo-codegen#384]
Currently, a generated TypeScript interface looks like this:
```ts
export interface CurrentUserQuery {
  // The currently authenticated user.
  // Returns null if the user is not authenticated.
  currentUser:  {
    // ...
  }
}
```
If instead apollo-codegen would use the JSDoc `/** ... */` syntax, editors like VS Code will show it as part of autocomplete/intellisense. Currently the very helpful descriptions from the schema are not surfaced in any meaningful way.

The above would need to change to:
```ts
export interface CurrentUserQuery {
  /**
   * The currently authenticated user.
   * Returns null if the user is not authenticated.
   */
  currentUser: {
    // ...
  }
}
```

**Comment by prencher** [comment]
As a follow-up, this should also be done for enums, where values are currently being postfixed with a `//` comment:
```
export enum BadgeClickAction {
  GET_BITS = "GET_BITS", // Go to the Bits purchasing page.
}
```

Similarly, this would be better:
```
export enum ClickAction {
  /** Redirect the user to the badge click URL. */
  VISIT_URL = "VISIT_URL",
}
```

**Comment by TedDriggs** [comment]
I'm about to submit a PR for this; it turned out to be a pretty straightforward change.

**Comment by jcready** [comment]
@shadaj @TedDriggs @prencher this issue needs to be re-opened as the changes that were made appear to have gotten over-written when the changeover to the mono-repo/modern versions happened.
