### ISSUE TITLE
double star (**) in glob does not recursively include subdirectories

### ISSUE THREAD

**Issue by majelbstoat** [apollographql/apollo-codegen#395]
I have a directory structure like:

```
graphql
  mutations
    mutation_a.graphql
    mutation_b.graphql
  queries
    query_1.graphql
  fragments
    users
      user_fragment_x.graphql
      user_fragment_y.graphql
```

where, for example, one of the mutations has

```
#import ../fragments/users/user_fragment_x.graphql
```

I run codegen as follows:

```
apollo-codegen generate app/lib/apollo/graphql/**/*.graphql --schema app/lib/apollo/generated/schema.json
```

Which I expect to compile all the schema and fragments.

However, I get this error:

```
.../mutations/mutation_a.graphql: Unknown fragment "UserX".
```

If I run codegen as follows:

```
apollo-codegen app/lib/apollo/graphql/**/**/*.graphql generate app/lib/apollo/graphql/**/*.graphql --schema app/lib/apollo/generated/schema.json
```

(note the additional `**/**/* syntax`) the command completes successfully.

My expectation is that double star includes all directories recursively, matching what I believe to be the standard for that glob syntax, and mirroring, for example nodemon, but it appears to only include directories one level deep.

**Comment by bs1180** [comment]
I was having this issue and a combination of [upgrading bash](https://gist.github.com/reggi/475793ea1846affbcfe8) and [adding quotes](https://github.com/apollographql/apollo-codegen/issues/180) solved it. My working command in package.json looks like this: 
``` 
"apollo:codegen": "apollo-codegen generate \"src/**/*.{ts,tsx}\" --schema schema.json --target typescript --output otypes.ts --addTypename"
```

**Comment by majelbstoat** [comment]
Thank you for the tip :) When I do that, each file is added in such a way that they appear to be processed individually. Because I have client-side schema definitions to work around `@client` directive issues, that leads to `The ObjectInput definition is not executable` errors. For whatever reason, keeping the definition unquoted, and with both glob formats works.

**Comment by mike-marcacci** [comment]
Adding quotes was the magic I needed!

**Comment by majelbstoat** [comment]
Closing, given the existence of a simple workaround.
