### ISSUE TITLE
Operation name is duplicated in generated types

### ISSUE THREAD

**Issue by peterschussheim** [apollographql/apollo-codegen#396]
### Problem

Is it possible to disable the logic in `apollo-codegen` that when generating types, appends the operation type to the generated flow/ts type?  Or is there an argument to disable this behavior?

### Example

For example, given the following named query in my client application:
```
export const SNIPPET_QUERY = gql`
  query SnippetQuery($id: ID!) {
    snippet(id: $id) {
      id
      description
      content
      isPublic
      owner {
        name
      }
    }
  }
`
```

`apollo-codegen` produces `flow` types that look like the following:
```
export type SnippetQueryQueryVariables = {|
  id: string,
|};

export type SnippetQueryQuery = {|
  snippet: ? {|
    __typename: "Snippet",
    id: string,
    description: string,
    content: string,
    isPublic: boolean,
    owner: {|
      __typename: "User",
      name: string,
    |},
  |},
|};
```

See `SnippetQueryQueryVariables` and `SnippetQueryQuery`.

Am I using this package incorrectly?  Thank you.

**Comment by martijnwalraven** [comment]
You're not using this package incorrectly, but I think most people don't postfix their queries with `Query`. So in this case, they would use `query Snippet`. 

It may make sense to not append the operation type when it is already part of the operation name.

**Comment by peterschussheim** [comment]
Thanks for that suggestion @martijnwalraven, those queries and mutations postfixed were my mistake.   I will close this issue.

**Comment by joshua7v** [comment]
@martijnwalraven hi, I have a question

what if the operation name is kind of the same as mutation name?

```gql
  mutation CreateUser ($createUserInput: CreateUserInput!) {
    createUser(data: $createUserInput) {
      # ... selection set
    }
  }
```

this will give an error like `There can be only one operation named "CreateUser"`

**Comment by martijnwalraven** [comment]
@joshua7v What is the issue here? Where does the other `CreateUser` operation come from?

**Comment by joshua7v** [comment]
@martijnwalraven thanks for the quick reply

ok, after some testing, it seems it's my bad.
sorry to bother you. have a nice day.
