### ISSUE TITLE
Adding Serializable marker to generated java types?

### ISSUE THREAD

**Issue by jcihocki** [apollographql/apollo-codegen#430]
It seems like it would be an easy win for android adoption to add the Serializable marker to generated java types. In androidland objects passed between components must be able to be persisted and re-inflated to support IPC and state saving/restoration. 

A cursory inspection of the generated code didn't yield usage of any types that would prevent serialization:

Primitives: 👍
enums: 👍
Strings: 👍
Maps and lists: I didn't go crazy deep but it seems like the types are serializable 🤷‍♂️ Are there some that aren't? 

Happy to help with this or undertake it myself if there's support.

**Comment by martijnwalraven** [comment]
You should probably open this issue on https://github.com/apollographql/apollo-android, because the Apollo Android team doesn't really watch this repo and the actual Java codegen doesn't live here.
