### ISSUE TITLE
[0.20.x] Output generated Types next to the source files (ts-modern behavior)

### ISSUE THREAD

**Issue by jbbr** [apollographql/apollo-codegen#449]
It's nice so get the flexibility to output types in any directory with `0.20.0+`.
But especially for projects which where using the previous behavior but also for projects with lot's of queries I liked the way the `ts-modern` target placed the types next to the query files.

Do you plan to support the old "types next to source" approach again?

**Comment by lirbank** [comment]
It does not look like it -> https://github.com/apollographql/apollo-codegen/blob/master/CHANGELOG.md#v0200

**Comment by shadaj** [comment]
This is fixed in https://github.com/apollographql/apollo-codegen/pull/447
