### ISSUE TITLE
apollo-codegen is not recognized

### ISSUE THREAD

**Issue by hopstad** [apollographql/apollo-codegen#453]
Hello.

I'm struggling to get apollo-codegen to work on Windows.

I have installed it with npm install apollo-codegen

But in terminal trying to run "apollo-codegen something" im getting 'apollo-codegen' is not recognized as an internal or external command,operable program or batch file.

Is there something more that needs to be done for getting it to work?

**Comment by iamdanthedev** [comment]
you could try `node_modules/.bin/apollo-codegen  your-command`

**Comment by iamdanthedev** [comment]
from the root folder of your project

**Comment by hopstad** [comment]
Thanks m8. Worked like a charm running from the .bin folder
