### ISSUE TITLE
Nested inputs with variables have undefined as value in arguments 

### ISSUE THREAD

**Issue by dcronje** [apollographql/apollo-codegen#47]
Hi, I have been using this library for the past 2 months and it is fantastic (app for an animal shelter), but I added a package to Carthage this evening and upgraded, now the generated API file is not being generated correctly. I have a rather large query which fetches the bulk of the data and I have structured my GraphQL schema with nested inputs I have not changed the schema and it was previously working.

Here is the query (I have left out the fragments):

`
query AllData($facilityId:ID, $squareImageWidth:Float!, $aspectImageWidth:Float!, $cityId:ID) {
  viewer {
    allAnimals(order:NAME filters: { facilityId: $facilityId, cityId: $cityId }) {
      list {
        ...AnimalFragment
      }
      count
    }
    allFacilities(order: NAME, filters: { cityId: $cityId }) {
      list {
        ...FacilityFragment
      }
      count
    }
    allLocations(order: NAME, filters: { locationType:[ADOPTION_LOCATION], cityId: $cityId }) {
      list {
        ...LocationFragment
      }
      count
    }
    allCountries(order: NAME) {
      list {
        ...CountryFragment
      }
      count
    }
    allCities(order: NAME) {
      list {
        ...CityFragment
      }
      count
    }
  }
}
`

but I now get undefined for all those variables in the generated code:

`
public struct Viewer: GraphQLMappable {
      public let __typename: String
      public let allAnimals: AllAnimal?
      public let allFacilities: AllFacility
      public let allLocations: AllLocation
      public let allCountries: AllCountry
      public let allCities: AllCity

      public init(reader: GraphQLResultReader) throws {
        __typename = try reader.value(for: Field(responseName: "__typename"))
        allAnimals = try reader.optionalValue(for: Field(responseName: "allAnimals", arguments: ["order": "NAME", "filters": ["facilityId": undefined, "cityId": undefined]]))
        allFacilities = try reader.value(for: Field(responseName: "allFacilities", arguments: ["order": "NAME", "filters": ["cityId": undefined]]))
        allLocations = try reader.value(for: Field(responseName: "allLocations", arguments: ["order": "NAME", "filters": ["locationType": ["ADOPTION_LOCATION"], "cityId": undefined]]))
        allCountries = try reader.value(for: Field(responseName: "allCountries", arguments: ["order": "NAME"]))
        allCities = try reader.value(for: Field(responseName: "allCities", arguments: ["order": "NAME"]))
      }
etc...

`

the shelter I am developing this for is hosting a huge event in a few weeks and I need to get this complete, please any help would be much appreciated.

Thanks.

**Comment by martijnwalraven** [comment]
Good to hear you like the library! 

I looked into it, and this turns out to be a bug in the way we generate code for field arguments when nested fields contain variables.

I should be able to get a fix for this out tomorrow.

**Comment by dcronje** [comment]
Thank you so much, really appreciate it and once again the library is awesome.

**Comment by martijnwalraven** [comment]
@dcronje: This should be fixed in `apollo-codegen` 0.10.4.

**Comment by dcronje** [comment]
thanks again, working perfectly.
