### ISSUE TITLE
Error running apollo-codegen after installing 0.10.4

### ISSUE THREAD

**Issue by davidmuzi** [apollographql/apollo-codegen#48]
Ive installed `apollo-codegen` globally, which is at version .10.4: 
```
/usr/local/lib
└─┬ apollo-codegen@0.10.4
```

When running the iOS sample apps, I get the following error:
```
/usr/local/lib/node_modules/apollo-codegen/lib/cli.js:33
_process2.default.on('unhandledRejection', error => {
                                                 ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:953:3
error: The version of Apollo.framework in your project requires the use of version 0.9 of apollo-codegen, but an unknown older version seems to be installed.
```

- It seems to work from command line:
`apollo-codegen download-schema http://localhost:8080/graphql --output schema.json`
- So it may be how its [executed from Xcode](https://github.com/apollographql/apollo-ios-quickstart/blob/master/StarWarsAPI/StarWarsAPI.xcodeproj/project.pbxproj#L188).
- Seems to work fine on 0.10.0

**Comment by martijnwalraven** [comment]
It seems you're running `apollo-codegen` on an older version of Node that doesn't support arrow functions. I'm not sure why it allowed you to install it, because `apollo-codegen` specifies it requires Node 4 in the `engines` field of its `package.json`.

Could you check which Node version you have installed and selected (if using NVM for example)?

**Comment by davidmuzi** [comment]
v7.4.0

**Comment by martijnwalraven** [comment]
Is there any chance you also have NVM or nodenv installed, and these specify an older version of Node?

Maybe you're not currently sourcing them in your shell, which is why you get the right version from the command line. But the script we use from Xcode checks for NVM or nodenv explicitly (see [here](https://github.com/apollographql/apollo-ios/blob/master/scripts/check-and-run-apollo-codegen.sh#L13-L25)) so it could still be picking an older installation up.

**Comment by lewisf** [comment]
Fat arrow functions should get compiled now before the package is published. Please try a newer version of apollo-codegen. If you're still running into this problem, feel free to re-open!

**Comment by alvinvgeorge** [comment]
I get the error as : error: The version of Apollo.framework in your project requires the use of version 0.10 of apollo-codegen, but 0.14.3 seems to be installed.

I fixed it as : 

1. run as root in terminal.
cd sudo -i


2. move to node_modules directory
cd /usr/local/lib/node_modules

3. install the required Apollo-codegen version
npm install apollo-codegen@0.10

**Comment by brascene** [comment]
I've faced the same error @alvinvgeorge , npm install at 0.10 worked for me also. Thanks!

**Comment by lewisf** [comment]
ping @martijnwalraven the above mentioned looks like a separate issue with an integration point. looks like a different issue than what was originally reported. not sure how you want to handle this, but let me know if I can help in anyway

**Comment by AnandWalvekar** [comment]
Hi @martijnwalraven 
On building Xcode project I got error
"The version of Apollo.framework in your project requires the use of version 0.10 of apollo-codegen, but 0.16.5 seems to be installed"
I don't think downgrading to 0.10 would be the solution. Please let me know what should we take the call on this?

**Comment by martijnwalraven** [comment]
@alvinvgeorge @brascene @AnandWalvekar: The latest release 0.6.2 of Apollo iOS requires version 0.16.x of `apollo-codegen` and should install it if necessary. What version of Apollo iOS are you running, and how did you install the framework (CocoaPods, Carthage, manually)?

**Comment by AnandWalvekar** [comment]
@martijnwalraven 
I use CocoaPods. The problem was with 
Apollo (0.5.6) & with apollo-codegen@0.16.5 
Which I resolved temporarily with 
Apollo (0.5.6) & with apollo-codegen@0.10

Now I can see below works like charm
Apollo (0.6.2) with apollo-codegen@0.16.5 
Thank you very much for the support.
