### ISSUE TITLE
Non-nullable types in TypeScript

### ISSUE THREAD

**Issue by danvk** [apollographql/apollo-codegen#55]
Looking through [the tests][1] for TypeScript codegen, the only non-nullable fields are scalars. Is this a limitation of the codegen or of GraphQL?

```ts
export interface HeroAndFriendsNamesQuery {
  hero: {
    name: string,
    friends: Array< {
      name: string,
    } > | null,
  } | null;
}
```

[1]: https://github.com/apollographql/apollo-codegen/blob/91d5e081d994da89ef54f453ac37da919a914a89/test/typescript/codeGeneration.js#L138-L145

**Comment by lewisf** [comment]
@danvk can you clarify what you are hoping to have instead?

**Comment by danvk** [comment]
Sure -- something like:

```ts
export interface HeroAndFriendsNamesQuery {
  hero: {
    name: string,
    friends: Array< {
      name: string,
    },
  };
}
```

where `here` and `friends` aren't nullable.

**Comment by lewisf** [comment]
The typescript generator will output non-null types if the GraphQL type is GraphQLNonNull, so whatever that can wrap is what codegen will generate as non-null.

**Comment by smkhalsa** [comment]
@danvk were you able to figure this one out? My graphql schema looks like this:

```
type Item {
  id: ID! @unique
  name: String!
  children: [Item!]!
}
```

but my generated type is still coming out as nullable:

```
export interface ItemQuery {
  item:  {
    id: string,
    children:  Array< {
      id: string,
      name: string,
    } > | null,
  } | null,
};

```
