### ISSUE TITLE
Doesn't import GraphQL fragments

### ISSUE THREAD

**Issue by clayne11** [apollographql/apollo-codegen#59]
I'm following the fragment colocation suggestion as outlined [here](http://dev.apollodata.com/react/webpack.html) but `apollo-codegen` doesn't seem to be following the import.

**Comment by martijnwalraven** [comment]
`apollo-codegen` doesn't currently support this Webpack loader `#import` syntax, but all `.graphql` files are concatenated and treated as one document, so you can still use fragments defined in other files.

**Comment by stubailo** [comment]
Yeah it should work just fine as long as you have apollo-codegen consume all of your `.graphql` files, since the imports are carefully designed so that other tools don't need to be aware of them.

**Comment by clayne11** [comment]
I got it working, thanks guys. The tooling around GraphQL is amazing, I'm
so exited to be using it in my production app! I just signed up for Apollo
Optics as well, very exciting.
