### ISSUE TITLE
Generate Flow response objects as exact

### ISSUE THREAD

**Issue by finneganh** [apollographql/apollo-codegen#62]
Flow types that represent response values (rather than input values) could probably be defined as “exact” objects, using `{| |}` instead of `{ }`. See: https://flowtype.org/docs/objects.html#exact-object-types

Per the above link, “Exact object types are a very useful tool for helping Flow to refine unions of object types and notice typos on property names and refinements.”

**Comment by martijnwalraven** [comment]
I haven't used Flow myself, but that sounds right! Do you want to submit a PR for this?

**Comment by finneganh** [comment]
Sure, I'll give it a shot. Will also see what the consequences are for making the input types exact and see if that's worth doing, too.

**Comment by finneganh** [comment]
The way that fragments are combined with `&` makes this not viable right now, because combining exact objects leads to an exact intersection which then typically doesn’t match anything.

Flow is planning to add a spread operator to combine objects within the next few releases, so I can get back to this then.
