### ISSUE TITLE
Optional arrays in the scheme become non optional

### ISSUE THREAD

**Issue by victorrr** [apollographql/apollo-codegen#69]
In my scheme there is a non optional array called genres. 
`genres: [String!]`

In the API.swift file it is not optional
`public let genres: [String]`

Error:

```
▿ Optional<Error>
  ▿ some : GraphQLResultError
    ▿ path : 7 elements
      - 0 : "viewer"
      - 1 : "market"
      - 2 : "channels"
      - 3 : "edges"
      - 4 : "0"
      - 5 : "node"
      - 6 : "genres"
    - underlying : Apollo.JSONDecodingError.nullValue
```

**Comment by martijnwalraven** [comment]
I just tried this out and haven't been able to reproduce it. Are you sure your schema contains `[String!]` and your `schema.json` is up to date?

**Comment by victorrr** [comment]
I was using an older version of apollo-codegen (0.9.4) . With 0.10.9 version my genres are now optional in the API.swift. With the 0.10.9 version I get an error in the API.swift file but its not related to this issue so I'll close this one and create one for that. Thank you @martijnwalraven
