### ISSUE TITLE
GraphQLResultReader variables member missing

### ISSUE THREAD

**Issue by victorrr** [apollographql/apollo-codegen#71]
I bumped to version 0.10.9 and get an error I didn't get with version 0.9.4 for the same query. 

The GraphQLResultReader doesn't have a variables member.

API.swift with my query and the xCode error:
![skarmavbild 2017-03-08 kl 11 22 26](https://cloud.githubusercontent.com/assets/116061/23700170/519c7f18-03f2-11e7-9877-e392cfa2738d.png)

**Comment by martijnwalraven** [comment]
What version of Apollo iOS are you using? `variables` was added in 0.5.0 (we're at 0.5.6 now). But you should have received a warning from the `check-and-run-apollo-codegen.sh` script if the `apollo-codegen` version didn't match, so I'm not sure what that didn't happen.

**Comment by victorrr** [comment]
I didn't get the warning but after updating Apollo iOS it works fine.

**Comment by martijnwalraven** [comment]
Are you running `apollo-codegen` manually? Or through a build phase with the `check-and-run-apollo-codegen.sh` script?

**Comment by victorrr** [comment]
No Im running it manually

**Comment by martijnwalraven** [comment]
Good to hear the problem isn't with `check-and-run-apollo-codegen.sh` :)  That would have generated an error message when the installed version of `apollo-codegen` doesn't match the version of Apollo iOS in your project.

**Comment by victorrr** [comment]
Thank you @martijnwalraven!
