### ISSUE TITLE
Flow generation incorrectly PascalCases all type names

### ISSUE THREAD

**Issue by jacobk** [apollographql/apollo-codegen#72]
The following line
https://github.com/apollographql/apollo-codegen/blob/master/src/flow/codeGeneration.js#L81
optimistically `PascalCase`s all type names even if they might in fact not be.

I agree `PascalCase` is conventional for naming GraphQL types but I can't find that it's required.

I was trying to generate flow annotations against a schema that contained types with `camelCase` names. This caused fields referencing the type to remain in `camelCase` whereas the definition of the type was in `PascalCase`

**Comment by chrishandorf** [comment]
Same issue here.  For a Bill Of Material (BOM) GraphQL schema I have this:

saveProductBOM(productBOM: InputProductBOM) : String
input InputProductBOM {  ... }

But the generated code looks like this:

export interface InputProductBom { ... }   /* this changes the case of "BOM" */

export interface SaveProductBomMutationVariables {
  inputProductBOM: InputProductBOM;       /* this keeps the case of "BOM" as is */
}

The result is a compile error.

**Comment by lewisf** [comment]
Consolidating case related issues into #92
