### ISSUE TITLE
apollo-codegen generate produces different schema.ts files on different platforms

### ISSUE THREAD

**Issue by un33k** [apollographql/apollo-codegen#78]
**Bug:**
The schema.ts changes depending on which env it was last generated on. Without any code change.

**Steps:**
apollo-codegen generate $PATH/**/*.gql --schema $PATH/doc.json --target typescript --output $PATH/schema.ts

1. Run the above command on macOS Sierra (node v6.9.5), and save the schema.ts and submit it to your repository.

2. Check out your code on Ubuntu (node v6.9.5) and run the above command again.
3. Diff the schema.ts

You'd see that the schema.ts has changed. Nothing is removed and nothing is added.  Just the order of some interfaces has changed.

**Cause:**
It is possible that $PATH/**/*.gql produces a different sorted list on OSX and Linux as `sort` may be different going from one OS to another.

**Side effect**
This doesn't break anything and everything works fine.  However, in a group development environment, every time the codegen is executed in different env, it will produce a change which may require an unnecessary repo submission.

**Comment by danvk** [comment]
If you're running different command lines on different platforms (due to shell expansion and the file system), then it's not too surprising that you get different results.

You could work around this by normalizing the order:

```
apollo-codegen generate $(ls $PATH/**/*.gql | sort) --schema $PATH/doc.json --target typescript --output $PATH/schema.ts
```

**Comment by un33k** [comment]
@danvk Yeah, I ended up sorting the files prior to passing them to codegen. Thx.
