### ISSUE TITLE
installation issues with apollo-codegen

### ISSUE THREAD

**Issue by modond** [apollographql/apollo-codegen#84]
> apollo-codegen@0.10.9 prepublish /Users/moniquehaas/apollo-codegen
> rm -rf lib && npm run compile

> apollo-codegen@0.10.9 compile /Users/moniquehaas/apollo-codegen
> babel src --out-dir lib --source-maps

ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/moniquehaas/apollo-codegen/.babelrc" at 0, attempted to resolve relative to "/Users/moniquehaas/apollo-codegen"
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! apollo-codegen@0.10.9 compile: `babel src --out-dir lib --source-maps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apollo-codegen@0.10.9 compile script 'babel src --out-dir lib --source-maps'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apollo-codegen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --out-dir lib --source-maps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apollo-codegen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apollo-codegen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/moniquehaas/apollo-codegen/npm-debug.log

npm ERR! addLocal Could not install /Users/moniquehaas/apollo-codegen
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "apollo-codegen"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! apollo-codegen@0.10.9 prepublish: `rm -rf lib && npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apollo-codegen@0.10.9 prepublish script 'rm -rf lib && npm run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apollo-codegen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf lib && npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apollo-codegen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apollo-codegen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/moniquehaas/npm-debug.log

**Comment by martijnwalraven** [comment]
Does this happen when you `npm install -g apollo-codegen`? Or are you installing from a local fork?

**Comment by modond** [comment]
I have a git clone repository locally. But I do  a global npm install; `npm install -g apollo-codegen` (I even cleaned up all of my node- and npm installations en then reinstalled them, just to be sure it was not an npm issue. But it does not seem to be.. as I can npm other repo's without any problems

**Comment by martijnwalraven** [comment]
I may be misunderstanding what you're trying to accomplish, but if you want to run `apollo-codegen` form a local repository the usual process would be to use `npm link` instead of `npm install`. Is there a reason you're not using that?

If you're actively developing the codegen code you can use `npm run watch` to watch for file changes and automatically recompile.

**Comment by modond** [comment]
What I am trying to accomplish is a development environment for apollo and therefore apollo codegen. I downloaded the repository to have a look at the files, not really to have a local repository. I reported the problem because I suspected there to be a problem with 'babel src --out-dir lib --source-maps' in the script of apollo-codegen. As I de installed and reinstalled all node and npm and the problem persisted I thought you may like to know about the issue..

**Comment by martijnwalraven** [comment]
What do you mean when you say the problem persisted? What steps did you follow to get the output you posted?

I just reinstalled npm, cloned a fresh repo, and did an `npm install` followed by `npm link`. That installs a development copy of `apollo-codegen`. I also tried `npm install -g apollo-codegen` on a clean install, and that installs `apollo-codegen` from npm as usual.

Is that similar to what you tried? Or am I missing something?

**Comment by modond** [comment]
Thank you Martijn. This is what I did:  npm for apollo, went fine, then I went on to `npm install -g apollo-codegen` got my first error (same as above) Then I cleaned up my npm and node using https://github.com/brock/node-reinstall. And I npm-ed apollo, went fine again and   I `npm install -g apollo-codegen` and got the same error as above.

**Comment by martijnwalraven** [comment]
What do you mean when you say you did npm for apollo or npm-ed apollo? What command did you use here?

**Comment by modond** [comment]
Oh sorry,  I did not npm apollo! I followed this instruction from the apollo  website: "You can also manually clone the apollo-ios repository, drag Apollo.xcodeproj into your project or workspace, add a dependency on Apollo.framework to your target." And that went fine..

**Comment by martijnwalraven** [comment]
So you also get the error when you just use `npm install -g apollo-codegen`, without cloning the repo? Have you still not been able to install it successfully?

What is weird to me is that your output mentions executing `prepublish` and `compile`, which shouldn't happen if you're just installing the precompiled package from npm.

**Comment by modond** [comment]
Yes I get the same error when I am using `npm install -g apollo-codegen`. And I wondered about the output that mentions `rm -rf lib && npm run compile` What is happening here? Is the lib replaced somewhere? Then again babel seems to be complaining about a missing lib? `babel src --out-dir lib --source-maps`. My knowledge is to shallow to understand what is happening here. I wish I could understand it better to pinpoint why I am running into this error while when you rebuild it nothing really bad is happening.

**Comment by martijnwalraven** [comment]
As with many npm packages, Babel is used to transpile source written using modern JavaScript to more broadly compatible code. The output of this is stored in `lib`, and that is what is published to npm. So executing Babel should only happen during development or when publishing the package, not when installing from npm.

The output mentions `/Users/moniquehaas/apollo-codegen`, which I assume is where you checked out the source. Can you retry `npm install -g apollo-codegen` from another directory?

**Comment by modond** [comment]
BINGO! I made a new testdirectory and did `npm install -g apollo-codegen` and it worked beautifully. Thank you! Now do I put my Xcode project (the one with apollo.xcodeproj) in that directory? So that it will find the codegen when needed (blissfully ignorant .. :-) )  Something babel in /Users/moniquehaas is maybe causing the problem? (sorry still trying to understand it, so that I do not run into it again..)

**Comment by martijnwalraven** [comment]
You can put your Xcode project wherever you want. The script phase you added to it will run the globally installed `apollo-codegen`.

Yes, you may have a stray `node_modules` in `/Users/moniquehaas` or higher up that is being picked up when you run npm from there.

**Comment by modond** [comment]
Thank you very much! You pulled me through. Now happily onto experimenting with GraphQL and Apollo! Noting the stray and putting it on my node "need to learn and understand better list" for the end of the week. Have a great day!
