### ISSUE TITLE
Generated TS annotations do not include __typename

### ISSUE THREAD

**Issue by chrissm79** [apollographql/apollo-codegen#89]
I have a `GraphQLUnionType` registered and based on the `__typename` my React app will dynamically render the correct component. However, when I generate typescript annotations, the `__typename` field is never included and I cannot manually add it without getting the error `Apollo inserts __typename automatically when needed, please do not include it explicitly`. Shouldn't the `__typename` be generated automatically and included in the annotations?

Thanks!

**Comment by lewisf** [comment]
hey @chrissm79. this is definitely a known issue and is a result of apollo-codegen having targetted swift as it's first target.

i'm hoping to tackle this issue in: https://github.com/apollographql/apollo-codegen/pull/86. stay tuned!
