### ISSUE TITLE
Missing description generation for top level operation fields

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-codegen#90]
Here is an example of generated IR:
```
{
	"operations": [
		{
                        ...
			"source": "query TestQuery {\n  hero {\n    __typename\n    name\n  }\n}",
			"fields": [
				{
					"responseName": "hero",
					"fieldName": "hero",
					"type": "Character",
					"fields": [
						{
							"responseName": "name",
							"fieldName": "name",
							"type": "String!",
							"description": "The name of the character"
						}
					],
					"fragmentSpreads": [],
					"inlineFragments": []
				}
			],
			"fragmentsReferenced": []
		}
	],
	"fragments": [],
	"typesUsed": []
}
```

Top level field hero (`operations.fields`) is missing `description` field. 
Field `fieldName`: `hero` should have description from `Character` interface.

This is how interface `Character` defined in schema:
```

          "kind": "INTERFACE",
          "name": "Character",
          "description": "A character from the Star Wars universe",
```

**Comment by sav007** [comment]
@martijnwalraven

**Comment by martijnwalraven** [comment]
I don't think there is an issue with top level operation fields. Those will include a description if one has been defined in the schema.

In this case however, the `hero` field doesn't actually include a description. The description you list is the one defined for the `Character` interface, so it is the description of the type of the field, not the field itself.

We could include the description from the field type in case the field itself doesn't have one, but I'm wondering if that always makes sense.

**Comment by sav007** [comment]
Oh yeah you are right sorry, closing
