### ISSUE TITLE
Move to Jest + Snapshot testing

### ISSUE THREAD

**Issue by lewisf** [apollographql/apollo-codegen#93]
The last change that was committed to add description to IR broke a bunch of tests because of the `description` field is now missing from a lot of the assertions.

I think it makes sense to take the chance to move to Jest + Snapshot testing so that when we change things that do change a bunch of test output, we can just tell Jest to update all the snapshots rather than us having to manually update all the assertions.

The nice thing about doing this is that in the future -- if we are to update something that updates a bunch of the output at any step of codegen, Jest will tell us exactly what changed where so that we can confirm that our changes are sane.

There are other Snapshot libraries for Mocha that are popping up but none of them look very mature yet. I've done the transition from Mocha to Jest on a much larger project before (all of Coursera's frontend) so this transition for `apollo-codegen` should be pretty quick :)

Thoughts @martijnwalraven ?

**Comment by martijnwalraven** [comment]
This sounds like a great idea! Having to update all these tests after every little change is a big pain, so that is why I got lazy with that last commit :)

Glad to hear you have experience with transitioning to Jest, really happy you want to take this on!
