### ISSUE TITLE
Empty generated file regardless of target

### ISSUE THREAD

**Issue by abdulhaq-e** [apollographql/apollo-codegen#98]
I get empty files regardless of the target. The input file was the results of introspecting the schema using both the introspection command provided by this tool and the one provided by the GraphQL server (they are the same anyway). The server implementation is `graphene` (in particular `graphene-django`).

An example generated file with TS as the target:

```ts
//  This file was automatically generated and should not be edited.
/* tslint:disable */
/* tslint:enable */
```

Here is a pastebin of the schema, the `types` and `directives` are non empty arrays. The former is quite large, if it's important I can fill some of it. https://pastebin.com/FuY3DNMd

**Comment by martijnwalraven** [comment]
Have you also written queries and put these in `.graphql` files? `apollo-codegen` generates query-specific types, so without queries there is nothing to generate :)

**Comment by abdulhaq-e** [comment]
Okay, that is something I was missing. I thought it would generate types for the whole graph. Thanks a lot.

**Comment by altschuler** [comment]
This was also unclear to me. It would be super useful if it actually did generate interfaces for all the types.
